# Path: /Users/caoguangpei/个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_platformdata/pc/throw/__init__.pyc
# RelativePath: clientlogic/cl_platformdata/pc/throw/__init__.pyc
# Source Generated with Decompyle++
# File: __init__.pyc (Python 3.6)

from cl_only import ReadOnly
g_GardenerAimThrow = { }
g_GardenerDirectPosRadius = { }
g_GardenerElementType = { }
g_GardenerCreateMonsterInfo = { }
from cl_commondefines import DAM_TYPE_CORRISION, DAM_TYPE_FIRE, DAM_TYPE_THUNDER, GARDENER_THROW_TYPE_CREATEMONSTER, GARDENER_THROW_TYPE_DIVIDEDEXPLODE, GARDENER_THROW_TYPE_EXPLODEBARREL, GARDENER_THROW_TYPE_JAR, GARDENER_THROW_TYPE_NORMALBOOM, GARDENER_THROW_TYPE_PLANT
g_GardenerAimThrow = ReadOnly({
    4211: GARDENER_THROW_TYPE_NORMALBOOM,
    4243: GARDENER_THROW_TYPE_NORMALBOOM,
    4244: GARDENER_THROW_TYPE_NORMALBOOM,
    4245: GARDENER_THROW_TYPE_NORMALBOOM,
    4253: GARDENER_THROW_TYPE_DIVIDEDEXPLODE,
    4301: GARDENER_THROW_TYPE_EXPLODEBARREL,
    4302: GARDENER_THROW_TYPE_EXPLODEBARREL,
    4306: GARDENER_THROW_TYPE_EXPLODEBARREL,
    4105: GARDENER_THROW_TYPE_JAR,
    1103: GARDENER_THROW_TYPE_PLANT,
    1104: GARDENER_THROW_TYPE_PLANT,
    4103: GARDENER_THROW_TYPE_JAR,
    4104: GARDENER_THROW_TYPE_JAR,
    4106: GARDENER_THROW_TYPE_JAR,
    4107: GARDENER_THROW_TYPE_JAR,
    4117: GARDENER_THROW_TYPE_JAR,
    4118: GARDENER_THROW_TYPE_CREATEMONSTER,
    4119: GARDENER_THROW_TYPE_CREATEMONSTER,
    4120: GARDENER_THROW_TYPE_CREATEMONSTER,
    4121: GARDENER_THROW_TYPE_CREATEMONSTER,
    4213: GARDENER_THROW_TYPE_JAR,
    4214: GARDENER_THROW_TYPE_JAR,
    4258: GARDENER_THROW_TYPE_JAR,
    6964: GARDENER_THROW_TYPE_EXPLODEBARREL,
    6965: GARDENER_THROW_TYPE_EXPLODEBARREL,
    4122: GARDENER_THROW_TYPE_JAR,
    4123: GARDENER_THROW_TYPE_JAR,
    4124: GARDENER_THROW_TYPE_JAR,
    4125: GARDENER_THROW_TYPE_JAR,
    4126: GARDENER_THROW_TYPE_JAR,
    4127: GARDENER_THROW_TYPE_JAR,
    4128: GARDENER_THROW_TYPE_JAR,
    4129: GARDENER_THROW_TYPE_JAR,
    4130: GARDENER_THROW_TYPE_JAR,
    4131: GARDENER_THROW_TYPE_JAR,
    4132: GARDENER_THROW_TYPE_JAR,
    4133: GARDENER_THROW_TYPE_JAR,
    4134: GARDENER_THROW_TYPE_JAR,
    2001: GARDENER_THROW_TYPE_NORMALBOOM,
    2002: GARDENER_THROW_TYPE_NORMALBOOM,
    2003: GARDENER_THROW_TYPE_NORMALBOOM,
    2004: GARDENER_THROW_TYPE_NORMALBOOM,
    2006: GARDENER_THROW_TYPE_NORMALBOOM,
    2021: GARDENER_THROW_TYPE_NORMALBOOM,
    2022: GARDENER_THROW_TYPE_NORMALBOOM,
    2041: GARDENER_THROW_TYPE_NORMALBOOM,
    2043: GARDENER_THROW_TYPE_NORMALBOOM,
    2061: GARDENER_THROW_TYPE_NORMALBOOM,
    2062: GARDENER_THROW_TYPE_NORMALBOOM,
    2063: GARDENER_THROW_TYPE_NORMALBOOM,
    2064: GARDENER_THROW_TYPE_NORMALBOOM,
    2065: GARDENER_THROW_TYPE_NORMALBOOM,
    2081: GARDENER_THROW_TYPE_NORMALBOOM,
    2082: GARDENER_THROW_TYPE_NORMALBOOM,
    2083: GARDENER_THROW_TYPE_NORMALBOOM,
    2084: GARDENER_THROW_TYPE_NORMALBOOM,
    2085: GARDENER_THROW_TYPE_NORMALBOOM,
    2086: GARDENER_THROW_TYPE_NORMALBOOM,
    2087: GARDENER_THROW_TYPE_NORMALBOOM,
    2089: GARDENER_THROW_TYPE_NORMALBOOM,
    2101: GARDENER_THROW_TYPE_NORMALBOOM,
    2102: GARDENER_THROW_TYPE_NORMALBOOM,
    2103: GARDENER_THROW_TYPE_NORMALBOOM,
    2105: GARDENER_THROW_TYPE_NORMALBOOM,
    2106: GARDENER_THROW_TYPE_NORMALBOOM,
    2108: GARDENER_THROW_TYPE_NORMALBOOM,
    2109: GARDENER_THROW_TYPE_NORMALBOOM,
    2110: GARDENER_THROW_TYPE_NORMALBOOM,
    2112: GARDENER_THROW_TYPE_NORMALBOOM,
    2121: GARDENER_THROW_TYPE_NORMALBOOM,
    2122: GARDENER_THROW_TYPE_NORMALBOOM,
    2123: GARDENER_THROW_TYPE_NORMALBOOM,
    2124: GARDENER_THROW_TYPE_NORMALBOOM,
    2125: GARDENER_THROW_TYPE_NORMALBOOM,
    2126: GARDENER_THROW_TYPE_NORMALBOOM,
    2128: GARDENER_THROW_TYPE_NORMALBOOM,
    2131: GARDENER_THROW_TYPE_NORMALBOOM,
    2133: GARDENER_THROW_TYPE_NORMALBOOM,
    2141: GARDENER_THROW_TYPE_NORMALBOOM,
    2142: GARDENER_THROW_TYPE_NORMALBOOM,
    2143: GARDENER_THROW_TYPE_NORMALBOOM,
    2145: GARDENER_THROW_TYPE_NORMALBOOM,
    2161: GARDENER_THROW_TYPE_NORMALBOOM,
    2162: GARDENER_THROW_TYPE_NORMALBOOM,
    2163: GARDENER_THROW_TYPE_NORMALBOOM,
    2164: GARDENER_THROW_TYPE_NORMALBOOM,
    2165: GARDENER_THROW_TYPE_NORMALBOOM,
    2181: GARDENER_THROW_TYPE_NORMALBOOM,
    2182: GARDENER_THROW_TYPE_NORMALBOOM,
    2183: GARDENER_THROW_TYPE_NORMALBOOM,
    2201: GARDENER_THROW_TYPE_NORMALBOOM,
    2202: GARDENER_THROW_TYPE_NORMALBOOM,
    2203: GARDENER_THROW_TYPE_NORMALBOOM,
    2205: GARDENER_THROW_TYPE_NORMALBOOM,
    2206: GARDENER_THROW_TYPE_NORMALBOOM,
    2221: GARDENER_THROW_TYPE_NORMALBOOM,
    2222: GARDENER_THROW_TYPE_NORMALBOOM,
    2223: GARDENER_THROW_TYPE_NORMALBOOM,
    2224: GARDENER_THROW_TYPE_NORMALBOOM,
    2241: GARDENER_THROW_TYPE_NORMALBOOM,
    2242: GARDENER_THROW_TYPE_NORMALBOOM,
    2243: GARDENER_THROW_TYPE_NORMALBOOM,
    2244: GARDENER_THROW_TYPE_NORMALBOOM,
    2281: GARDENER_THROW_TYPE_NORMALBOOM,
    2282: GARDENER_THROW_TYPE_NORMALBOOM,
    2283: GARDENER_THROW_TYPE_NORMALBOOM,
    2285: GARDENER_THROW_TYPE_NORMALBOOM,
    2301: GARDENER_THROW_TYPE_NORMALBOOM,
    2321: GARDENER_THROW_TYPE_NORMALBOOM,
    1105: GARDENER_THROW_TYPE_PLANT,
    2361: GARDENER_THROW_TYPE_NORMALBOOM,
    2381: GARDENER_THROW_TYPE_NORMALBOOM,
    2383: GARDENER_THROW_TYPE_NORMALBOOM,
    2385: GARDENER_THROW_TYPE_NORMALBOOM,
    2401: GARDENER_THROW_TYPE_NORMALBOOM,
    2402: GARDENER_THROW_TYPE_NORMALBOOM,
    2421: GARDENER_THROW_TYPE_NORMALBOOM,
    2422: GARDENER_THROW_TYPE_NORMALBOOM,
    2423: GARDENER_THROW_TYPE_NORMALBOOM,
    2088: GARDENER_THROW_TYPE_NORMALBOOM,
    2107: GARDENER_THROW_TYPE_NORMALBOOM,
    2127: GARDENER_THROW_TYPE_NORMALBOOM,
    2144: GARDENER_THROW_TYPE_NORMALBOOM,
    2245: GARDENER_THROW_TYPE_NORMALBOOM,
    3004: GARDENER_THROW_TYPE_NORMALBOOM,
    2091: GARDENER_THROW_TYPE_NORMALBOOM,
    2225: GARDENER_THROW_TYPE_NORMALBOOM,
    2134: GARDENER_THROW_TYPE_NORMALBOOM })
g_GardenerDirectPosRadius = ReadOnly({
    4211: 10 })
g_GardenerElementType = ReadOnly({
    4211: DAM_TYPE_FIRE,
    4243: DAM_TYPE_FIRE,
    4244: DAM_TYPE_CORRISION,
    4245: DAM_TYPE_THUNDER,
    2062: DAM_TYPE_FIRE,
    2063: DAM_TYPE_THUNDER,
    2064: DAM_TYPE_CORRISION,
    2108: DAM_TYPE_FIRE,
    2109: DAM_TYPE_THUNDER,
    2110: DAM_TYPE_CORRISION,
    2112: DAM_TYPE_CORRISION,
    2201: DAM_TYPE_FIRE,
    2203: DAM_TYPE_FIRE,
    2205: DAM_TYPE_THUNDER,
    2222: DAM_TYPE_FIRE,
    2223: DAM_TYPE_THUNDER,
    2224: DAM_TYPE_CORRISION,
    2242: DAM_TYPE_FIRE,
    2243: DAM_TYPE_THUNDER,
    2244: DAM_TYPE_CORRISION,
    2421: DAM_TYPE_CORRISION,
    2423: DAM_TYPE_CORRISION,
    2225: DAM_TYPE_FIRE })
g_GardenerCreateMonsterInfo = ReadOnly({
    4118: {
        3001: 24211 },
    4119: {
        3001: 20061 },
    4120: {
        3001: 20061 },
    4121: {
        3001: 20061 } })

def CheckValidGardenerAim(iModel):
    if iModel not in g_GardenerAimThrow:
        return False
    return True


def GetGardenerAimThrowType(iModel):
    return g_GardenerAimThrow[iModel]


def GetGardenerAimThrowRadius(iModel):
    if iModel not in g_GardenerDirectPosRadius:
        return 0
    return g_GardenerDirectPosRadius[iModel]


def GetGardenerAimThrowElementType(iModel):
    if iModel not in g_GardenerElementType:
        return 0
    return g_GardenerElementType[iModel]


def GetGardenerAimThrowCreateMonsterInfo(iModel, iWarNo):
    if iModel not in g_GardenerCreateMonsterInfo:
        return 0
    if iWarNo not in g_GardenerCreateMonsterInfo[iModel]:
        return 0
    return g_GardenerCreateMonsterInfo[iModel][iWarNo]

