# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_item/defines.pyc
# RelativePath: clientlogic/cl_item/defines.pyc
# Source Generated with Decompyle++
# File: defines.pyc (Python 3.6)

from cl_cscommondef.cs_itemdef import *
FOURTIMES_GUNSIGHT = 3026
SIXTIMES_GUNSIGHT = 3027
MSG_ITEM_ADD = 1001
MSG_ITEM_REMOVE = 1002
MSG_ITEM_HOLD = 1003
MSG_ITEM_UNHOLD = 1004
MSG_ITEM_FIRE = 1005
MSG_ITEM_BULLETMODIFY = 1006
MSG_ITEM_FILLBULLET = 1007
MSG_ITEM_REFRESHATTRIBUTE = 1008
MSG_ITEM_ENERGYBAR_CHANGE = 1009
MSG_ITEM_EXPLODE_CHANGE = 1010
MSG_ITEM_STARTUP_CHANGE = 1011
MSG_ITEM_MAXPFBULLET_CHANGE = 1012
MSG_ITEM_BULLETSIZE_CHANGE = 1013
MSG_ITEM_REPEAT_CHANGE = 1014
MSG_ITEM_REPEAT_END = 1015
SPECIAL_ATTR_MSG = {
    'EnergyBar': MSG_ITEM_ENERGYBAR_CHANGE,
    'ExplodeControl': MSG_ITEM_EXPLODE_CHANGE,
    'StartUpControl': MSG_ITEM_STARTUP_CHANGE,
    'BulletSize': MSG_ITEM_BULLETSIZE_CHANGE }
