# Path: /Users/caoguangpei/个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_platformdata/pc/servant/s302.pyc
# RelativePath: clientlogic/cl_platformdata/pc/servant/s302.pyc
# Source Generated with Decompyle++
# File: s302.pyc (Python 3.6)

from cl_commondefines import DEFEND_TREND_NONE, WARRIOR_ELITE, WARRIOR_NODURABILITY, WARRIOR_PLANT, WARRIOR_SUMMON_STELE
from cl_newformula import Func569, Func760, Func768, Func771, Func800, Func801
from cl_resmgr.resdata import CServantData as CCustom

class CServantData(CCustom):
    m_SID = 302
    m_Name = '植物'
    m_Shape = 1103
    m_FightType = WARRIOR_PLANT
    m_AttPerform = 7168
    m_PerformList = (7169,)
    m_DefaultPhase = 1
    m_PhasePF = {
        1: 5324,
        2: 5330,
        3: 5341 }
    m_Betree = 'Plant.PlantFsm'
    m_AIConfig = {
        'PFAI': 39247 }
    m_DefendTrend = DEFEND_TREND_NONE
    m_BaseAttrInfo = {
        1: {
            1: {
                'HPMax': (lambda *a: 8000 + Func800(*a)),
                'RHP': 0,
                'ArmorMax': 0,
                'ShieldMax': 0,
                'RShield': 0,
                'ShieldRecoverTime': 0,
                'DefPhysical': 0,
                'DefThunder': 0,
                'DefCorrision': 0,
                'DefFire': 0,
                'AccuracyProb': 100,
                'StruckIgnoreFrame': 0,
                'DefKnockBack': 0,
                'KnockBackFrame': 0,
                'DefThump': 0,
                'ThumpFrame': 0,
                'Att': (lambda *a: (50000 + Func569(*a) * 6000) * (1 + Func768(*a) / 10000)),
                'MoveSpeed': 0,
                'AttSpeed': (lambda *a: 75 * (1 + Func771(*a) / 10000)),
                'Toughness': 0,
                'TurnSpeed': 14,
                'TurnThresholdAngle': 0,
                'TurnInterval': 0,
                'AdsorbDis': 0,
                'HardEff': 0,
                'SaveTime': 0,
                'DodgeProb': 0,
                'IntervalTime': 0,
                'EnergyMax': 0,
                'REnergy': 0,
                'SpecialMHPWeight': 0,
                'LifeTime': (lambda *a: 9900 + Func760(*a, **{
'sAttr': 'PlantLifeTime' })),
                'HitRange': (lambda *a: 7 + Func801(*a)) },
            2: {
                'HPMax': (lambda *a: 20000 + Func800(*a)),
                'RHP': 0,
                'ArmorMax': 0,
                'ShieldMax': 0,
                'RShield': 0,
                'ShieldRecoverTime': 0,
                'DefPhysical': 0,
                'DefThunder': 0,
                'DefCorrision': 0,
                'DefFire': 0,
                'AccuracyProb': 100,
                'StruckIgnoreFrame': 0,
                'DefKnockBack': 0,
                'KnockBackFrame': 0,
                'DefThump': 0,
                'ThumpFrame': 0,
                'Att': (lambda *a: (120000 + Func569(*a) * 15000) * (1 + Func768(*a) / 10000)),
                'MoveSpeed': 0,
                'AttSpeed': (lambda *a: 75 * (1 + Func771(*a) / 10000)),
                'Toughness': 0,
                'TurnSpeed': 14,
                'TurnThresholdAngle': 0,
                'TurnInterval': 0,
                'AdsorbDis': 0,
                'HardEff': 0,
                'SaveTime': 0,
                'DodgeProb': 0,
                'IntervalTime': 0,
                'EnergyMax': 0,
                'REnergy': 0,
                'SpecialMHPWeight': 0,
                'LifeTime': (lambda *a: 9900 + Func760(*a, **{
'sAttr': 'PlantLifeTime' })),
                'HitRange': 99 } },
        2: {
            1: {
                'HPMax': (lambda *a: 8000 + Func800(*a)),
                'RHP': 0,
                'ArmorMax': 0,
                'ShieldMax': 0,
                'RShield': 0,
                'ShieldRecoverTime': 0,
                'DefPhysical': 0,
                'DefThunder': 0,
                'DefCorrision': 0,
                'DefFire': 0,
                'AccuracyProb': 100,
                'StruckIgnoreFrame': 0,
                'DefKnockBack': 0,
                'KnockBackFrame': 0,
                'DefThump': 0,
                'ThumpFrame': 0,
                'Att': (lambda *a: (50000 + Func569(*a) * 6000) * (1 + Func768(*a) / 10000)),
                'MoveSpeed': 0,
                'AttSpeed': (lambda *a: 75 * (1 + Func771(*a) / 10000)),
                'Toughness': 0,
                'TurnSpeed': 14,
                'TurnThresholdAngle': 0,
                'TurnInterval': 0,
                'AdsorbDis': 0,
                'HardEff': 0,
                'SaveTime': 0,
                'DodgeProb': 0,
                'IntervalTime': 0,
                'EnergyMax': 0,
                'REnergy': 0,
                'SpecialMHPWeight': 0,
                'LifeTime': (lambda *a: 9900 + Func760(*a, **{
'sAttr': 'PlantLifeTime' })),
                'HitRange': (lambda *a: 7 + Func801(*a)) },
            2: {
                'HPMax': (lambda *a: 20000 + Func800(*a)),
                'RHP': 0,
                'ArmorMax': 0,
                'ShieldMax': 0,
                'RShield': 0,
                'ShieldRecoverTime': 0,
                'DefPhysical': 0,
                'DefThunder': 0,
                'DefCorrision': 0,
                'DefFire': 0,
                'AccuracyProb': 100,
                'StruckIgnoreFrame': 0,
                'DefKnockBack': 0,
                'KnockBackFrame': 0,
                'DefThump': 0,
                'ThumpFrame': 0,
                'Att': (lambda *a: (120000 + Func569(*a) * 15000) * (1 + Func768(*a) / 10000)),
                'MoveSpeed': 0,
                'AttSpeed': (lambda *a: 75 * (1 + Func771(*a) / 10000)),
                'Toughness': 0,
                'TurnSpeed': 14,
                'TurnThresholdAngle': 0,
                'TurnInterval': 0,
                'AdsorbDis': 0,
                'HardEff': 0,
                'SaveTime': 0,
                'DodgeProb': 0,
                'IntervalTime': 0,
                'EnergyMax': 0,
                'REnergy': 0,
                'SpecialMHPWeight': 0,
                'LifeTime': (lambda *a: 9900 + Func760(*a, **{
'sAttr': 'PlantLifeTime' })),
                'HitRange': 99 } },
        3: {
            1: {
                'HPMax': (lambda *a: 8000 + Func800(*a)),
                'RHP': 0,
                'ArmorMax': 0,
                'ShieldMax': 0,
                'RShield': 0,
                'ShieldRecoverTime': 0,
                'DefPhysical': 0,
                'DefThunder': 0,
                'DefCorrision': 0,
                'DefFire': 0,
                'AccuracyProb': 100,
                'StruckIgnoreFrame': 0,
                'DefKnockBack': 0,
                'KnockBackFrame': 0,
                'DefThump': 0,
                'ThumpFrame': 0,
                'Att': (lambda *a: (50000 + Func569(*a) * 6000) * (1 + Func768(*a) / 10000)),
                'MoveSpeed': 0,
                'AttSpeed': (lambda *a: 75 * (1 + Func771(*a) / 10000)),
                'Toughness': 0,
                'TurnSpeed': 14,
                'TurnThresholdAngle': 0,
                'TurnInterval': 0,
                'AdsorbDis': 0,
                'HardEff': 0,
                'SaveTime': 0,
                'DodgeProb': 0,
                'IntervalTime': 0,
                'EnergyMax': 0,
                'REnergy': 0,
                'SpecialMHPWeight': 0,
                'LifeTime': (lambda *a: 9900 + Func760(*a, **{
'sAttr': 'PlantLifeTime' })),
                'HitRange': (lambda *a: 7 + Func801(*a)) },
            2: {
                'HPMax': (lambda *a: 20000 + Func800(*a)),
                'RHP': 0,
                'ArmorMax': 0,
                'ShieldMax': 0,
                'RShield': 0,
                'ShieldRecoverTime': 0,
                'DefPhysical': 0,
                'DefThunder': 0,
                'DefCorrision': 0,
                'DefFire': 0,
                'AccuracyProb': 100,
                'StruckIgnoreFrame': 0,
                'DefKnockBack': 0,
                'KnockBackFrame': 0,
                'DefThump': 0,
                'ThumpFrame': 0,
                'Att': (lambda *a: (120000 + Func569(*a) * 15000) * (1 + Func768(*a) / 10000)),
                'MoveSpeed': 0,
                'AttSpeed': (lambda *a: 75 * (1 + Func771(*a) / 10000)),
                'Toughness': 0,
                'TurnSpeed': 14,
                'TurnThresholdAngle': 0,
                'TurnInterval': 0,
                'AdsorbDis': 0,
                'HardEff': 0,
                'SaveTime': 0,
                'DodgeProb': 0,
                'IntervalTime': 0,
                'EnergyMax': 0,
                'REnergy': 0,
                'SpecialMHPWeight': 0,
                'LifeTime': (lambda *a: 9900 + Func760(*a, **{
'sAttr': 'PlantLifeTime' })),
                'HitRange': 99 } } }
    m_BaseHate = {
        'Default': 50,
        'FightType': {
            WARRIOR_NODURABILITY: 0,
            WARRIOR_SUMMON_STELE: 80,
            WARRIOR_ELITE: 100 },
        2201: 100,
        3905: 500,
        2202: 100,
        2341: 500,
        2342: 500,
        2343: 500,
        3925: 500 }
    m_HateDisEff = {
        'HeroDisEff': ((22, 0.7), (30, 0.5), (40, 0.3)),
        'ServantDisEff': ((5, 1), (15, 0.75)) }

