# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_msgcenter/defines.pyc
# RelativePath: clientlogic/cl_msgcenter/defines.pyc
# Source Generated with Decompyle++
# File: defines.pyc (Python 3.6)

MSG_WAR_DIE = 100
MSG_WAR_DIE_BEFORE = 101
MSG_WAR_KILL = 102
MSG_WAR_DP = 103
MSG_WAR_ATTACK = 104
MSG_WAR_ATTACKED = 105
MSG_WAR_ATTACK_END = 106
MSG_WAR_DIE_EXECUTE_BEFORE = 107
MSG_WAR_PERFORM_START = 108
MSG_WAR_PERFORM = 109
MSG_WAR_PERFORMED = 110
MSG_WAR_SCENEED = 111
MSG_WAR_PERFORM_END = 112
MSG_WAR_RECEIVEDAM = 113
MSG_WAR_RECEIVEDAMED = 114
MSG_WAR_STATE = 115
MSG_WAR_STATEED = 116
MSG_WAR_CURE = 117
MSG_WAR_CUREED = 118
MSG_WAR_PERFORM_HALT = 119
MSG_WAR_DYING = 120
MSG_WAR_DYING_END = 121
MSG_WAR_DIEDIST = 122
MSG_WAR_SERVANT_PERFORM_START = 123
MSG_WAR_WEAPONPERFROM_COSTBULLET = 124
MSG_WAR_GAMBLER_ROLL_RELIC = 125
MSG_WAR_INITGOODS = 126
MSG_WAR_SHOPREFRESH = 127
MSG_WAR_HP_CHANGE = 128
MSG_WAR_ATTR_CHANGE = 129
MSG_WAR_ACTIVE_SEASONSUIT = 130
MSG_WAR_WIELDWEAPON = 131
MSG_WAR_REMOVE_SEASONSUIT = 132
MSG_WAR_ADDITEM = 133
MSG_WAR_FUSEDRELIC = 134
MSG_WAR_DEALTOTALDAM = 135
MSG_WAR_REVTOTALDAM = 136
MSG_WAR_ADDSTATE = 137
MSG_WAR_ADDTALENT = 138
MSG_WAR_STATECOUNTCHANGE = 139
MSG_WAR_REDUCE_SUITCONDITION = 140
MSG_WAR_CHANGE_WEAPON = 142
MSG_WAR_UNHOLD_WEAPON = 143
MSG_WAR_SHIELD_CURE = 144
MSG_WAR_SHIELD_CUREED = 145
MSG_WAR_BULLETCHANGE = 147
MSG_WAR_TALENT_CHOOSE_BEFORE = 148
MSG_WAR_DUALSTATE = 149
MSG_WAR_THUMPED = 150
MSG_WAR_KNOCKBACKED = 151
MSG_WAR_GROUPHATE = 152
MSG_WAR_PICK = 153
MSG_WAR_COSTBULLET = 154
MSG_WAR_COSTRELIFES = 155
MSG_WAR_KILLMONSTERGROUP = 156
MSG_WAR_REWARDITEM = 157
MSG_WAR_SHIELD_RECOVER = 158
MSG_WAR_RELIFE = 159
MSG_WAR_GETMINIGAMETIME = 160
MSG_WAR_CAUSEDEBUFF = 161
MSG_WAR_PREDICTDAM = 162
MSG_WAR_PREDICTDAMED = 163
MSG_WAR_NPCINTERACT = 164
MSG_WAR_LEAVESCENE = 165
MSG_WAR_ADDPERFORMCD = 166
MSG_WAR_MOVESTATUSCHANGE = 167
MSG_WAR_GETWARCASH = 168
MSG_WAR_FINDHIDELEVEL = 169
MSG_WAR_REMOVERELIC = 170
MSG_WAR_REMOVEWEAPON = 171
MSG_WAR_WEAPONFIRE = 172
MSG_WAR_ENTERSCENE = 173
MSG_WAR_ATTACKPF = 174
MSG_WAR_MINIGAMEINIT = 175
MSG_WAR_COMCOSTBULLET = 176
MSG_WAR_COMADDBULLET = 177
MSG_WAR_CAUSEDFINALDEBUFF = 178
MSG_WAR_CREATESUMMON = 179
MSG_WAR_REMOVESUMMON = 180
MSG_WAR_TRIGGERSKILL = 181
MSG_WAR_TRIGGERCARTOON = 182
MSG_WAR_NPCCREATEOVER = 183
MSG_WAR_KILLALLMONSTER = 184
MSG_WAR_ADDRELIC = 185
MSG_WAR_REMOVENPC = 186
MSG_WAR_NPCSTOPINTERACT = 187
MSG_WAR_BREAKSHIELD = 188
MSG_WAR_SHIELDFINSH = 189
MSG_WAR_ADDWEAPON = 190
MSG_WAR_UPGRADEWEAPON = 191
MSG_WAR_RECASTWEAPON = 192
MSG_WAR_CAUSEMIXDEBUFF = 193
MSG_WAR_GOTDEBUFF = 194
MSG_WAR_BUYGOODS = 195
MSG_WAR_CUSTOMSTATEEND = 196
MSG_WAR_GETGOODSLIST = 197
MSG_WAR_ADDIMMOBILIZE = 198
MSG_WAR_ADDGSCASH = 199
MSG_WAR_OWNERGETMINIGAMETIME = 200
MSG_WAR_COMCOSTBAGBULLET = 202
MSG_WAR_ASSISTKILL = 203
MSG_WAR_BREAKARMOR = 204
MSG_WAR_SWITCH_ATT_PERFORM = 205
MSG_WAR_ENTERWATCH = 206
MSG_WAR_BUILD_INTERACT = 207
MSG_WAR_BUILD_STOP_INTERACT = 208
MSG_WAR_DROPREPLACE = 209
MSG_WAR_GENERATE_RELIC = 210
MSG_WAR_CHOOSE_RELIC = 211
MSG_WAR_ROOM_CHALLENGE = 212
MSG_WAR_REVTOTALCURE = 213
MSG_WAR_RESCUE = 214
MSG_WAR_THUNDEROVER = 215
MSG_WAR_ADD_MONSTERRELIC = 216
MSG_WAR_TRIGGER_CHALLENGE_EVENT = 217
MSG_WAR_TALENT_CHOOSE = 218
MSG_WAR_SAVERESET = 219
MSG_WAR_DROPWEAPON = 220
MSG_WAR_AFTERADDCASH = 221
MSG_WAR_GOTDEFINALDEBUFF = 222
MSG_WAR_GREATEWEAPON = 223
MSG_WAR_THUNDER = 224
MSG_WAR_EXPLOSION = 225
MSG_WAR_SHAREGOODS = 226
MSG_WAR_MONSTER_START_HATE = 227
MSG_WAR_MONSTER_END_HATE = 228
MSG_WAR_REMOVEOBJ = 229
MSG_WAR_CREATEMONSTER = 230
MSG_WAR_DROP = 231
MSG_WAR_DROPDISAPPEAR = 232
MSG_WAR_COST_ENERGY = 233
MSG_WAR_BARRIER_ACTIVE = 234
MSG_WAR_SWITCH_PHASE = 235
MSG_WAR_MONSTER_SUPER = 236
MSG_WAR_MODIFYPERFORMCD = 237
MSG_WAR_MONSTER_UPDATE_HATE = 238
MSG_WAR_ATTACK_SAME_SIDE = 239
MSG_WAR_ENTERROOM = 240
MSG_WAR_CONSUMEGSCASH = 241
MSG_WAR_BEFORE_REMOVE_RELIC_DROP = 242
MSG_WAR_USINGEMOTION = 243
MSG_WAR_GREATEDROPWEAPON = 244
MSG_WAR_REWARDRAREITEM = 245
MSG_WAR_ADDBENED = 246
MSG_WAR_ADD_INSCRIPTION = 247
MSG_WAR_DIE_BEFORE_MAIN = 248
MSG_WAR_OPEN_BEFOR_BENED = 249
MSG_WAR_ADD_ENERGY = 250
MSG_WAR_SHIELD_BLOCK = 251
MSG_WAR_SHIELD_RECEIVE = 252
MSG_WAR_SHIELD_HOLD = 253
MSG_WAR_RAREITEMGOODS = 254
MSG_WAR_USERAREITEM = 255
MSG_WAR_SWITCH_CAREER_PERFORM = 256
MSG_WAR_COSTWARCASH = 257
MSG_WAR_CHANGE_PLAYER_LINKSTATUS = 258
MSG_WAR_REFRESHRELIC = 259
MSG_WAR_EVENTNPC_REWARD_RELIC = 260
MSG_WAR_CHOOSE_RELIC_START = 261
MSG_WAR_RECYCLEDROP = 262
MSG_WAR_BEFORESMITHNPC = 263
MSG_WAR_PLAYERSETTLE = 264
MSG_WAR_REPLACEWEAPON = 265
MSG_WAR_EVENTNPC_REFRESH = 266
MSG_WAR_EVENTNPC_CHOOSE = 267
MSG_WAR_BEFOREREPLACEWEAPON = 268
MSG_WAR_CREATEBUILD = 269
MSG_WAR_ACREMOVEWEAPON = 270
MSG_WAR_BEFOREREMOVEWEAPON = 271
MSG_WAR_DISABLE_GEMINI = 272
MSG_WAR_TRIGGER_EXTERNALDRIVE = 273
MSG_WAR_BEFOREUNHOLDWEAPON = 274
MSG_WAR_AFTERADDWEAPON = 275
MSG_WAR_GAMBLER_MODIFY_GROOVENUM = 276
MSG_WAR_CUSTOM_USEPERFORM_BEFORE = 277
MSG_WAR_TALENT_GEN = 278
MSG_WAR_DROP_RELIC_REWARD = 279
MSG_WAR_BAGBULLETCHANGE_BEFOR = 280
MSG_WAR_BEFOREINTERACTSHOP = 281
MSG_WAR_MARKTARGET = 282
MSG_WAR_EVENTNPC_AFTERREWARD = 283
MSG_WAR_BEFORE_CHANGE_ENERGY = 284
MSG_WAR_CUSTOMSTATECOUNTCHANGE = 285
MSG_WAR_WEAPONPEOFROM_START = 286
MSG_WAR_WEAPON_ELEMENTTYPE_REFRESH = 287
MSG_WAR_REMOVEBENED = 288
MSG_WAR_CHOOSEBENED = 289
MSG_WAR_CHANGE_WEAPONBASEGRADE = 290
MSG_WAR_ENABLE_GEMINI = 291
MSG_WAR_WEAPON_BEFORECREATE = 292
MSG_WAR_UPGRADE = 293
MSG_WAR_MAIN_ATTACK = 294
MSG_WAR_UPGRADEREWARD_CHOOSE = 295
MSG_WAR_UPGRADEREWARD = 296
MSG_WAR_PLAYERLOGIN = 297
MSG_WAR_PLAYERMAPLOADOK = 298
MSG_WAR_PLAYERONREADY = 299
MSG_WAR_FORBID = 300
MSG_WAR_UNFORBID = 301
MSG_WAR_PLAYERLEAVEGAME = 302
MSG_WAR_PLAYERCHOOSELEAVEGAME = 303
MSG_WAR_CREATEHERO = 304
MSG_WAR_ADDRELICPERFORM = 305
MSG_WAR_REMOVETALENT = 306
MSG_WAR_ADDSUIT = 307
MSG_WAR_GENERATE_RELIC_BEFORE = 308
MSG_WAR_SURVIVOR_HANDLE_RELIC = 309
MSG_WAR_BEFOREDROPCASH = 310
MSG_WAR_ADDRAREGOLDENCUP = 311
MSG_WAR_TRIGGERQTE = 312
MSG_WAR_DROPRAREITEM = 313
MSG_WAR_CREATERAREGOLDENCUP = 314
MSG_WAR_GAMBLER_GET_COMB = 315
MSG_WAR_GAMBLER_GET_QUALITY = 316
MSG_WAR_GAMBLER_REPLACE_QUALITY = 317
MSG_WAR_GAMBLER_CLEAR_GROOVE = 318
MSG_WAR_GAMBLER_CLEAR_ALLGROOVE = 319
MSG_WAR_CHANGE_RELIC_SHOWQUALITY = 320
MSG_WAR_DROPTRIGGER = 325
MSG_WAR_BEFORECREATEDEMON = 326
MSG_WAR_RECYCLEGOLDENCUP = 327
MSG_WAR_MAGICPOWERCHANGE = 328
MSG_WAR_CLIENTACTIVEUSECOUNTCHANGE = 329
MSG_WAR_ADDRELICTALENT = 330
MSG_WAR_THUNDERPLUS = 331
MSG_WAR_CLEARIMMOBILIZE = 332
MSG_WAR_MAXBULLETCHANGE = 333
MSG_WAR_TALENT_CHOOSE_END = 334
MSG_WAR_RELIC_CHOOSE_END = 335
MSG_WAR_BARRIER_COLLIDED = 336
MSG_WAR_CHANGE_DEVICE_ENERGY = 337
MSG_WAR_CHANGE_DEVICE_ENERGY_BEFORE = 338
MSG_WAR_ADD_TOXICSTATE_COUNT = 339
MSG_WAR_BARRIER_BLOCK = 340
MSG_WAR_COSTPFBULLET = 341
MSG_WAR_ADD_DEVICE = 342
MSG_WAR_SUMMONSTELE_END = 343
MSG_WAR_HEROINSAFE = 344
MSG_WAR_DEVICE_INIT = 345
MSG_WAR_SUMMONSTELE_TRIGGER = 346
MSG_WAR_DESTROY_RELIC = 347
MSG_WAR_BEFORECREATEINKBEAD = 348
MSG_WAR_CONTROL_DEVICE = 349
MSG_WAR_ENABLE_DEVICECOMP_CHANGE = 350
MSG_WAR_GENERATE_DEVICECOMP = 351
MSG_WAR_BARRIER_THROUGH = 352
MSG_WAR_DEVICEACTIVE_COST_BEFORE = 353
MSG_WAR_RECYCLE_DEVICECOMP = 354
MSG_WAR_CHANGE_INKVALUE = 355
MSG_WAR_BEFORE_HEROTRIGGERINKAREA = 356
MSG_WAR_REMOVE_DEVICECOMP = 357
MSG_WAR_HIT_FLAW_BEFORE = 358
MSG_WAR_REFRESHGOLDENCUP = 359
MSG_WAR_ICE_MOVE = 360
MSG_WAR_INKWALL_BLOCK = 361
MSG_WAR_AFTER_ADD_TOXICSTATECOUNT = 362
MSG_WAR_INKAREADISAPPEAR_DUMP = 363
MSG_WAR_TRIGGERCRT_RANGECHECK = 364
MSG_WAR_INKAREASQUARERECORD_CHANGE = 365
MSG_WAR_CUSTOMSTATE_START = 366
MSG_WAR_SPAWNFLAW = 367
MSG_WAR_HALT_CASTINGSKILL = 368
MSG_WAR_PET_PASSIVESPELL_SETCD = 369
MSG_WAR_SET_CURPET = 370
MSG_WAR_SECCESSCONQUER_RECORD = 371
MSG_WAR_EXECUTE = 372
MSG_WAR_HANDLE_PET = 373
MSG_WAR_HATCH_PET = 374
MSG_WAR_BEFORE_INITPETABILITY = 375
MSG_WAR_BEFORE_INITFUSEPETABILITY = 376
MSG_WAR_USE_CAREERPF = 377
MSG_WAR_BEFORE_CHANGE_INKVALUE = 378
MSG_WAR_ADDPFBULLET = 379
MSG_WAR_MAXBAGBULLETCHANGE = 380
MSG_WAR_ADD_PET = 381
MSG_WAR_USE_THROWPF = 382
MSG_WAR_START_CONQUER = 383
MSG_WAR_ADD_PETEGG = 384
MSG_WAR_TAKEOVERHERO = 385
MSG_WAR_HANDOVERHERO = 386
MSG_WAR_ADD_MINICLONE = 387
MSG_WAR_MINICLONE_DIE = 388
MSG_WAR_UNLOCK = 389
MSG_WAR_PET_DIE = 390
MSG_WAR_CONTROL_SEASONSUIT = 391
MSG_WAR_PREADDRELIC = 392
MSG_WAR_SET_CORERELIC = 393
MSG_WAR_REMOVE_CORERELIC = 394
MSG_WAR_TRIGGERGATETRANSFER = 395
MSG_WAR_PFBULLETCHANGE = 396
MSG_WAR_PARRY = 397
MSG_WAR_ADDSUITPERFORM = 398
MSG_WAR_AUTOFILLBULLET = 399
MSG_WAR_APPEND_INSCRIPTION = 500
MSG_WAR_REMOVE_INSCRIPTION = 501
MSG_WAR_AFTERREMOVETALENT = 502
MSG_WAR_COMMONTALENT_GEN = 503
MSG_WAR_GEN_BEFOR_BENED = 504
MSG_WAR_ADDWEAPONCOM = 505
MSG_WAR_REMOVEWEAPONCOM = 506
MSG_WAR_SERVANT_FIGHT_START = 507
MSG_WAR_SERVANT_FIGHT_END = 508
MSG_WAR_ITEM_CHANGE_MODE = 509
MSG_WAR_TASK = 510
MSG_WAR_CAUSEUNBALANCE = 511
MSG_WAR_CHANGE_WEAPONGRADE = 512
MSG_WAR_RECAST_INSCRIPTION = 513
MSG_WAR_UPGRADE_INSCRIPTION = 514
MSG_WAR_REMOVESUIT = 515
MSG_WAR_PFNODEKILL = 516
MSG_WAR_CHANGERESISTANCE = 517
MSG_CMD_OPENSEASONPANEL = 518
MSG_WAR_PLAYERLEVELREPORT_BEFORE = 519
MSG_WAR_INSCRIPTION_DISABLE_ELEMENTTYPE = 520
MSG_WAR_INSCRIPTION_ENABLE_ELEMENTTYPE = 521
MSG_WAR_TALENT_GEN_CHANGE = 522
MSG_WAR_HATCH = 523
MSG_WAR_INSCRIPTION_STATE_REFRESH = 524
MSG_WAR_WUDI = 525
MSG_WAR_PFNODEKILLED_BEFORE = 526
MSG_WAR_PET_UPDATE_HATE = 527
MSG_WAR_CAUSE_ADDIMMOBILIZE = 528
MSG_WAR_CAUSE_CLEARIMMOBILIZE = 529
MSG_WAR_TRIGGERPETPERFORM = 530
MSG_WAR_SIGNALITEM = 531
MSG_WAR_REMOVEDEBUFF = 532
MSG_WAR_BULLETDROP = 533
MSG_WAR_UPDATE_STATECOUNTEFF = 534
MSG_WAR_REMOVEBENED_BEFORE = 535
MSG_WAR_BUYGSGOOD = 536
MSG_WAR_CHANGEBLANKRELICNUM = 537
MSG_WAR_PERFORM_ELEMENTTYPE_REFRESH = 538
MSG_WAR_UPDATESEASONSUITGRADE = 539
MSG_WAR_CREATEGOLDENCUP = 540
MSG_WAR_DEMON_DYNAMIC_REWARD = 541
MSG_WAR_GOODSPOSINITBEFORE = 542
MSG_WAR_DISABLETALENT_CHANGED = 543
MSG_WAR_DONEREWARD_RELICLOTTERY = 544
MSG_WAR_CAUSE_REDUCEACTIONSPEED = 546
MSG_WAR_HANDLE_TEMPRELIC = 547
MSG_WAR_REDUCESPEEDED = 548
MSG_WAR_REDUCESPEEDEDEND = 549
MSG_WAR_CAUSE_REDUCEACTIONSPEEDED = 550
MSG_WAR_CAUSE_REDUCEACTIONSPEEDEDEND = 551
MSG_WAR_ADD_REDUCESPEEDSTATE = 552
MSG_WAR_REMOVE_REDUCESPEEDSTATE = 553
MSG_WAR_WAND = 554
MSG_WAR_BEFOREREWARD_RELICLOTTERY = 555
MSG_WAR_CHANGEPERFORMCDRATIO = 556
MSG_WAR_MONSTER_SUPER_BEFORE = 557
MSG_WAR_UPGRADEREWARD_CREATE = 558
MSG_WAR_WANDCOMPCHANGE = 560
MSG_WAR_INVISIBLE_END = 561
MSG_WAR_WANDDISABLE = 562
MSG_WAR_WANDCHANGE = 563
MSG_WAR_INTERACT_PERFORM_HIT_TARGET = 564
MSG_WAR_CHARGECARTOON_TRIGGER = 565
MSG_WAR_WANDCOMP = 566
MSG_WAR_GARDENER_OPERATION_SEED = 567
MSG_WAR_GARDENER_OPERATION_PLANT = 568
MSG_WAR_WANDSHOP_BUY = 569
MSG_WAR_CONTINUESHOOT_END = 570
MSG_WAR_WANDENABLE = 571
MSG_WAR_WANDSHOP = 572
MSG_WAR_UPDATE_STRENGTHATT = 573
MSG_WAR_CHANGE_ITEMBASEGRADE_BEFORE = 574
MSG_WAR_WAND_ATTR_CHANGE = 575
MSG_WAR_DICECHANGE = 576
MSG_WAR_WANDSHOP_BEFORE_ROLL = 578
MSG_WAR_AFTER_CONSETDICEPOINT = 579
MSG_WAR_TRIGGERBURST = 580
MSG_WAR_CUSTOM_PERFORMINFO_CHANGE = 581
MSG_WAR_DICESHOP = 582
MSG_WAR_UPDATESKILLCOUNT = 584
MSG_WAR_FORCEDISABLE_RELIC = 585
MSG_WAR_PARASITIC = 586
MSG_WAR_IGNORESTATE_EFF = 587
MSG_WAR_CHANGE_DICEENERGY = 588
MSG_WAR_USEDICESPECIALITEM = 589
MSG_WAR_DICESHOP_BUY = 591
MSG_WAR_CHANGE_INK_STATUS = 592
MSG_WAR_CHANGE_BIGLION = 593
MSG_WAR_WEAPONPFBULLETCHANGE = 594
MSG_WAR_SET_HEROSIDEPET = 595
MSG_WAR_FOGPOISON = 596
MSG_WAR_S7_CONTAINER_OPERATION = 597
MSG_WAR_SEASONSHOP = 598
MSG_WAR_S7CRYSTALSHOPINIT = 599
MSG_WAR_SEASONITEMCHANGE = 600
MSG_WAR_S7SHOP = 601
MSG_WAR_CHANGEWEAPON_FROM_DIFFERENTWAEAPONCON = 602
MSG_WAR_MAIN_SKILL_DURATION = 603
MSG_WAR_S8THIRDACTIVE_STATE = 604
MSG_WAR_STHIRDACTIVE_ENERGY_CHANGE = 605
MSG_WAR_BULLETDROP_PLAYER = 606
MSG_WAR_S8THIRDACTIVE_ATT_REFRESH = 607
MSG_WAR_S8_CONTAINER_OPERATION = 608
MSG_CMD_MOVE = 321
MSG_CMD_OPENSNIPE = 322
MSG_CMD_JUMP = 323
MSG_CMD_SWITCHSNIPE = 324
MSG_WARMGR_ADDPLAYER = 400
MSG_WARMGR_REMOVEPLAYER = 401
MSG_WARMGR_LEVELNODEINIT = 403
MSG_WARMGR_STARTFIGHT = 404
MSG_WARMGR_LEVELNODEFINISH = 405
MSG_WARMGR_LEVELNODEGOALOK = 406
MSG_WARMGR_ADDALLPLAYER = 407
MSG_WARMGR_LEVELCTRLINIT = 408
MSG_WARMGR_CREATEMONSTER = 409
MSG_WARMGR_LEVELINIT_INITRELICDROPPROB = 410
MSG_WARMGR_INTERACTTRANSFER = 411
MSG_WARMGR_SCENELOAD = 412
MSG_WARMGR_TRANSFERENABLE = 413
MSG_WARMGR_ADDPLAYERINFO = 414
MSG_WARMGR_CG_END = 415
MSG_WARMSG_WEAPONGRADE = 416
MSG_WARMSG_INSCRIPTIONNUM = 417
MSG_WARMSG_PHASESTART = 418
MSG_WARMSG_PHASECHALLENGE = 419
MSG_WARMSG_TREASURERELIC = 420
MSG_WARMSG_RESTPHASE = 421
MSG_WARMGR_LEVELNODEFINISH_BEFORE = 422
MSG_WARMGR_CREATEMONSTER_BEFORE = 423
MSG_WARMGR_STARTENDLESS = 425
MSG_WARMGR_ENDLESS_TIMEOUT = 426
MSG_WARMGR_CG_START = 427
MSG_WARMGR_INITELEMENT = 428
MSG_WARMGR_SMASHOBSTACLE_CREATEMONSTER = 429
MSG_WARMGR_PREADDPLAYER = 430
MSG_WARMGR_CONQUERSUCCESS = 431
MSG_WARMGR_CONQUERCHALLENGE = 432
MSG_WARMGR_ADDBOSSRELIC = 433
MSG_LEVEL_CREATEMONSTER = 450
MSG_LEVEL_ROOMSTART = 451
MSG_LEVEL_ROOMGOAL = 452
MSG_LEVEL_ROOMCHALLENGE = 453
MSG_LEVEL_CREATEMONSTER_PRE = 454
MSG_LEVEL_STARTSPAWN = 455
MSG_LEVEL_PREROOMGOAL = 456
MSG_LEVEL_CREATENPC_PRE = 457
MSG_LEVEL_CHOOSECNT = 458
MSG_LEVEL_LAYERMONSTERCNT = 459
MSG_LEVEL_CHOOSEITEM = 460
MSG_LEVEL_ROOMCHALLENGESTART = 461
MSG_LEVEL_CHOOSECHALLENGE = 462
MSG_LEVEL_REPLACECHALLENGE_PRE = 463
MSG_LEVEL_LAYERSTART = 464
MSG_LEVEL_BEFORE_CHOOSEBOSSLEVEL = 465
MSG_LEVEL_ROOMCHALLENGE_CREATEDEMON = 466
MSG_LEVEL_CHOOSENPC_PRE = 467
MSG_LEVEL_LEVELROOMDOORTRIGGER = 468
MSG_LEVEL_TRIGGERGATECTRL = 470
MSG_WAR_EVENTNPC_CHOOSE_RELIC = 471
MSG_LEVEL_BEFORE_CREATEINITOBSTACLE = 472
MSG_LEVEL_CHOOSECHALLENGE_BEFORE = 473
MSG_LEVEL_AFTER_SETSEASONCHALLENGEPOINT = 474
MSG_LEVEL_COMMON_ROOMCHALLENGE = 475
MSG_UNSEND_CGEVENT = 997
MSG_UNSEND_CLIENTBUTTON = 998
MSG_UNSEND_SCENEEVT = 999
MSG_HASSUB_LIST = {
    MSG_WAR_S8THIRDACTIVE_ATT_REFRESH: 1,
    MSG_WAR_S8_CONTAINER_OPERATION: 1,
    MSG_WAR_COMCOSTBAGBULLET: 1,
    MSG_WAR_BULLETCHANGE: 1,
    MSG_WARMGR_CONQUERCHALLENGE: 1,
    MSG_WAR_UNFORBID: 1,
    MSG_WAR_FORBID: 1,
    MSG_WAR_WAND: 1,
    MSG_WAR_HANDLE_TEMPRELIC: 1,
    MSG_WAR_PERFORM_ELEMENTTYPE_REFRESH: 1,
    MSG_WAR_PET_UPDATE_HATE: 1,
    MSG_WAR_WUDI: 1,
    MSG_WAR_INSCRIPTION_STATE_REFRESH: 1,
    MSG_WAR_CAUSEUNBALANCE: 1,
    MSG_WAR_TASK: 1,
    MSG_WAR_BEFORESMITHNPC: 1,
    MSG_WAR_RECYCLEDROP: 1,
    MSG_WAR_GOTDEFINALDEBUFF: 1,
    MSG_WAR_STHIRDACTIVE_ENERGY_CHANGE: 1,
    MSG_WAR_S8THIRDACTIVE_STATE: 1,
    MSG_WAR_MAIN_SKILL_DURATION: 1,
    MSG_WAR_S7SHOP: 1,
    MSG_WAR_SEASONITEMCHANGE: 1,
    MSG_LEVEL_COMMON_ROOMCHALLENGE: 1,
    MSG_WAR_SEASONSHOP: 1,
    MSG_WAR_S7_CONTAINER_OPERATION: 1,
    MSG_WAR_FOGPOISON: 1,
    MSG_WAR_SET_HEROSIDEPET: 1,
    MSG_WAR_WEAPONPFBULLETCHANGE: 1,
    MSG_WAR_CHANGE_BIGLION: 1,
    MSG_WAR_CHANGE_INK_STATUS: 1,
    MSG_WAR_DICESHOP_BUY: 1,
    MSG_WAR_CHANGE_DICEENERGY: 1,
    MSG_WAR_PARASITIC: 1,
    MSG_WAR_DICESHOP: 1,
    MSG_WAR_DICECHANGE: 1,
    MSG_WAR_WANDSHOP: 1,
    MSG_WAR_GARDENER_OPERATION_PLANT: 1,
    MSG_WAR_GARDENER_OPERATION_SEED: 1,
    MSG_WAR_WANDCOMP: 1,
    MSG_WAR_CHARGECARTOON_TRIGGER: 1,
    MSG_WAR_WANDCHANGE: 1,
    MSG_WAR_WANDCOMPCHANGE: 1,
    MSG_WAR_GOODSPOSINITBEFORE: 1,
    MSG_WAR_DEMON_DYNAMIC_REWARD: 1,
    MSG_WAR_PFBULLETCHANGE: 1,
    MSG_WAR_CONTROL_SEASONSUIT: 1,
    MSG_WAR_MAXBAGBULLETCHANGE: 1,
    MSG_WAR_HATCH_PET: 1,
    MSG_WAR_HANDLE_PET: 1,
    MSG_WAR_SET_CURPET: 1,
    MSG_WAR_TRIGGERCRT_RANGECHECK: 1,
    MSG_WAR_BEFORE_HEROTRIGGERINKAREA: 1,
    MSG_WAR_CHANGE_INKVALUE: 1,
    MSG_WAR_BARRIER_THROUGH: 1,
    MSG_WAR_CONTROL_DEVICE: 1,
    MSG_WAR_BARRIER_BLOCK: 1,
    MSG_WAR_CHANGE_DEVICE_ENERGY_BEFORE: 1,
    MSG_WAR_CHANGE_DEVICE_ENERGY: 1,
    MSG_WAR_ADDRELICTALENT: 1,
    MSG_WAR_TALENT_CHOOSE_BEFORE: 1,
    MSG_WAR_WEAPON_ELEMENTTYPE_REFRESH: 1,
    MSG_WAR_BEFOREUNHOLDWEAPON: 1,
    MSG_WARMSG_TREASURERELIC: 1,
    MSG_WARMSG_PHASECHALLENGE: 1,
    MSG_WAR_GENERATE_RELIC_BEFORE: 1,
    MSG_WAR_BEFORE_REMOVE_RELIC_DROP: 1,
    MSG_WAR_ENTERSCENE: 1,
    MSG_WAR_LEAVESCENE: 1,
    MSG_WAR_PREDICTDAM: 1,
    MSG_WAR_TRIGGERCARTOON: 1,
    MSG_WAR_CAUSEDFINALDEBUFF: 1,
    MSG_WAR_CAUSEDEBUFF: 1,
    MSG_WAR_PICK: 1,
    MSG_WAR_DUALSTATE: 1,
    MSG_WAR_AFTERADDCASH: 1,
    MSG_WAR_RESCUE: 1,
    MSG_WAR_MAIN_ATTACK: 1,
    MSG_WAR_WEAPONFIRE: 1,
    MSG_WAR_DEALTOTALDAM: 1,
    MSG_WAR_ATTR_CHANGE: 1,
    MSG_WAR_PERFORM_HALT: 1,
    MSG_WAR_CURE: 1,
    MSG_WAR_STATE: 1,
    MSG_WAR_RECEIVEDAM: 1,
    MSG_WAR_PERFORM_END: 1,
    MSG_WAR_PERFORM: 1,
    MSG_WAR_PERFORM_START: 1,
    MSG_WAR_ATTACK_END: 1,
    MSG_WAR_ATTACKPF: 1,
    MSG_WAR_ATTACK: 1,
    MSG_WAR_DP: 1,
    MSG_WAR_ASSISTKILL: 1,
    MSG_WAR_KILL: 1,
    MSG_WAR_DIE: 1 }
MSGSUBOFFSET = 10000
MSGSUBMAX = 120

def InitSubMsg():
    for iMsg in MSG_HASSUB_LIST:
        g_Sub_Msg_Key[iMsg] = { }
        for i in range(MSGSUBMAX):
            g_Sub_Msg_Key[iMsg][i] = (i * MSGSUBOFFSET + iMsg, iMsg)
        
    

g_Sub_Msg_Key = { }
InitSubMsg()

def GetMsgKey(iMsg, iSub):
    if iSub < 0:
        iSub = 0
    return iSub * MSGSUBOFFSET + iMsg


def SplitMsgAndSub(iKey):
    iSub = iKey // MSGSUBOFFSET
    if iSub == 0:
        iSub = -1
    return (iKey % MSGSUBOFFSET, iSub)

g_Core_Msg = {
    MSG_WARMGR_LEVELNODEFINISH: 1,
    MSG_WARMGR_LEVELNODEFINISH_BEFORE: 1,
    MSG_WAR_PLAYERONREADY: 1,
    MSG_WAR_PLAYERMAPLOADOK: 1 }
