# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_commondefines/cd_seasonplay.pyc
# RelativePath: clientlogic/cl_commondefines/cd_seasonplay.pyc
# Source Generated with Decompyle++
# File: cd_seasonplay.pyc (Python 3.6)

CRTSTAL_RAWMATERIAL = 99
CRTSTAL_ONEDIR = 1
CRTSTAL_TWODIR = 2
CRTSTAL_THREEDIR = 3
CRTSTAL_FOURDIR = 4
CRTSTAL_FIVEDIR = 5
SEASONSHOP_INITGOODSBEFORE = 1
SEASONSHOP_INITS7GOODS = 2
SEASONSHOP_BUYS7CRYSTAL = 3
SEASONSHOP_BUYS7PACKET = 4
S7SHOP_ADD_CRYSTALGOODS = 1
S7CRYSTAL_ADD = 1
S7MODULE_ADD = 2
S7CRYSTAL_POINTADD = 3
S7MODULE_ENHANCE = 4
S7MODULE_AUTOENHANCE = 5
S7MODULE_DECREASE = 6
S7CRYSTAL_REMOVE = 7
S7MODULE_REMOVE = 8
S7ITEM_REFRESH = 9
SEASONPASSIVE_TAG_S8_COMMON = 1
SEASONPASSIVE_TAG_S8_THIRDCOMMON = 2
SEASONPASSIVE_TAG_S8_THIRDSPECIAL = 3
