# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_commondefines/cd_season.pyc
# RelativePath: clientlogic/cl_commondefines/cd_season.pyc
# Source Generated with Decompyle++
# File: cd_season.pyc (Python 3.6)

WARRIOR_SEASONREWARD = 1
HERO_SEASONREWARD = 2
SPWARRIOR_SEASONREWARD = 3
REWARDPOOL_STATE_NONE = 0
REWARDPOOL_STATE_LOCK = 1
REWARDPOOL_STATE_PEOGRESS = 2
REWARDPOOL_STATE_FINISH = 3
REWARDPOOLNODE_STATE_NONE = 0
REWARDPOOLNODE_STATE_LOCK = 1
REWARDPOOLNODE_STATE_NORMAL = 2
REWARDPOOLNODE_STATE_FINISH = 3
S7MODULE_TAG_WEAPON = 0
S7MODULE_TAG_CAREER = 1
S7MODULE_TAG_THROW = 2
S7MODULE_TAG_ELEMENT = 3
S7MODULE_TAG_MINOR = 4
S7MODULE_TAG_MODESPEED = 5
S7MODULE_TAG_WEAPONCRAZYEFF = 6
S7MODULE_TAG_FIRESTONE = 7
S7MODULE_TAG_TOXICFOG = 8
S7MODULE_TAG_THUNDERKNIFE = 9
S7MODULE_TAG_COOMONPERFROM = 10
S7MODULE_TAG_BLOOM = 11
S7MODULE_TAG_SURVIVAL = 12
BEFORE_ADDCOUNT = 1
AFTER_ADDCOUNT = 2
S7_ALL_PERFORM_ENABLE = 1
S7_MODULE_POINT_CHANGE = 2
S7_AUTO_EQUIP = 3
S7_AUTO_UNEQUIP = 4
S7GOODS_SINGLE_DEPOLY = 0
S7GOODS_ALL_DEPOLY = 1
S8_GOODS_QUALITY_BLUE = 1
S8_GOODS_QUALITY_PURPLE = 2
S8_GOODS_QUALITY_ORANGE = 3
S8_THIRDITEM_ENABLE = 1
S8_THIRDITEM_DISABLE = 2
S8_THIRDITEM_REMOVE = 3
S8THIRDACTIVE_REFRESH_MAXENERGY = 1
S8THIRDACTIVE_REFRESH_ENERGYCOST = 2
S8THIRDACTIVE_REFRESH_RECOVERINTERVAL = 3
S8THIRDACTIVE_REFRESH_RECOVERVALUE = 4
