# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_resmgr/aitempparam.pyc
# RelativePath: clientlogic/cl_resmgr/aitempparam.pyc
# Source Generated with Decompyle++
# File: aitempparam.pyc (Python 3.6)

from cl_commondefines.cd_other import *
g_AITempParam = {
    MONSTERAI_TYPE_HATESEARCH: {
        PARAM_LEVEL_FAR_LOW: {
            'ShowWarning': 0,
            'ShowCatchAni': 1,
            'SceneAttentionArea': None,
            'PatrolFaceAngle': 360,
            'PatrolFaceTime': 100,
            'PatrolFace': None,
            'GuardTime': 120,
            'ViewR': 99,
            'ViewAngle': 180,
            'GuardDis': 99,
            'SearchDis': 99,
            'NearDis': 2,
            'BroadcastCatch': 0,
            'UseGroupHate': 1,
            'GroupHateDelay': 0,
            'BackToBornPos': 0,
            'ShowPosID': None,
            'DodgeMaxTimes': 1,
            'DodgeCD': 300 },
        PARAM_LEVEL_MEDIUM_LOW: {
            'ShowWarning': 0,
            'ShowCatchAni': 1,
            'SceneAttentionArea': None,
            'PatrolFaceAngle': 360,
            'PatrolFaceTime': 100,
            'PatrolFace': None,
            'GuardTime': 120,
            'ViewR': 99,
            'ViewAngle': 180,
            'GuardDis': 99,
            'SearchDis': 99,
            'NearDis': 2,
            'BroadcastCatch': 0,
            'UseGroupHate': 1,
            'GroupHateDelay': 0,
            'BackToBornPos': 0,
            'ShowPosID': None,
            'DodgeMaxTimes': 1,
            'DodgeCD': 300 },
        PARAM_LEVEL_CLOSE_HIGH: {
            'ShowWarning': 0,
            'ShowCatchAni': 1,
            'SceneAttentionArea': None,
            'PatrolFaceAngle': 360,
            'PatrolFaceTime': 100,
            'PatrolFace': None,
            'GuardTime': 120,
            'ViewR': 99,
            'ViewAngle': 180,
            'GuardDis': 99,
            'SearchDis': 99,
            'NearDis': 2,
            'BroadcastCatch': 0,
            'UseGroupHate': 1,
            'GroupHateDelay': 0,
            'BackToBornPos': 0,
            'ShowPosID': None,
            'DodgeMaxTimes': 2,
            'DodgeCD': 300 },
        PARAM_LEVEL_FAR_HIGH: {
            'ShowWarning': 0,
            'ShowCatchAni': 1,
            'SceneAttentionArea': [],
            'PatrolFaceAngle': 360,
            'PatrolFaceTime': 100,
            'PatrolFace': [
                360,
                100],
            'GuardTime': 120,
            'ViewR': 99,
            'ViewAngle': 180,
            'GuardDis': 99,
            'SearchDis': 99,
            'NearDis': 2,
            'BroadcastCatch': 0,
            'UseGroupHate': 1,
            'GroupHateDelay': 0,
            'BackToBornPos': 0,
            'ShowPosID': [],
            'DodgeMaxTimes': 2,
            'DodgeCD': 300 },
        PARAM_LEVEL_MEDIUM_HIGH: {
            'ShowWarning': 0,
            'ShowCatchAni': 1,
            'SceneAttentionArea': [],
            'PatrolFaceAngle': 360,
            'PatrolFaceTime': 100,
            'PatrolFace': [
                360,
                100],
            'GuardTime': 120,
            'ViewR': 99,
            'ViewAngle': 180,
            'GuardDis': 99,
            'SearchDis': 99,
            'NearDis': 4,
            'BroadcastCatch': 0,
            'UseGroupHate': 1,
            'GroupHateDelay': 0,
            'BackToBornPos': 0,
            'ShowPosID': [],
            'DodgeMaxTimes': 2,
            'DodgeCD': 300 },
        PARAM_LEVEL_CLOSE_LOW: {
            'ShowWarning': 0,
            'ShowCatchAni': 1,
            'SceneAttentionArea': [],
            'PatrolFaceAngle': 360,
            'PatrolFaceTime': 100,
            'PatrolFace': [
                360,
                100],
            'GuardTime': 120,
            'ViewR': 99,
            'ViewAngle': 180,
            'GuardDis': 99,
            'SearchDis': 99,
            'NearDis': 4,
            'BroadcastCatch': 0,
            'UseGroupHate': 1,
            'GroupHateDelay': 0,
            'BackToBornPos': 0,
            'ShowPosID': [],
            'DodgeMaxTimes': 1,
            'DodgeCD': 300 } },
    MONSTERAI_TYPE_DEFAULT: {
        PARAM_LEVEL_FAR_LOW: {
            'GuerrillaInterval': 400,
            'GuerrillaAttack': 1,
            'GuerrillaProb': 50,
            'RangedPosMinDis': 5,
            'RangedPosMaxDis': 7,
            'RangedPosMinAngle': 90,
            'RangedPosMaxAngle': 105,
            'RangedPosR': 20,
            'HideR': 10,
            'HideTime': 400,
            'HideAttackStandingTime': 100,
            'FuzzyInterval': 400,
            'FuzzyProb': 50 },
        PARAM_LEVEL_MEDIUM_LOW: {
            'GuerrillaInterval': 400,
            'GuerrillaAttack': 1,
            'GuerrillaProb': 50,
            'RangedPosMinDis': 4,
            'RangedPosMaxDis': 6,
            'RangedPosMinAngle': 75,
            'RangedPosMaxAngle': 105,
            'RangedPosR': 15,
            'HideR': 10,
            'HideTime': 400,
            'HideAttackStandingTime': 100,
            'FuzzyInterval': 400,
            'FuzzyProb': 50 },
        PARAM_LEVEL_CLOSE_HIGH: {
            'GuerrillaInterval': 200,
            'GuerrillaAttack': 1,
            'GuerrillaProb': 100,
            'RangedPosMinDis': 3,
            'RangedPosMaxDis': 5,
            'RangedPosMinAngle': 75,
            'RangedPosMaxAngle': 105,
            'RangedPosR': 10,
            'HideR': 10,
            'HideTime': 200,
            'HideAttackStandingTime': 100,
            'FuzzyInterval': 200,
            'FuzzyProb': 100 },
        PARAM_LEVEL_FAR_HIGH: {
            'GuerrillaInterval': 200,
            'GuerrillaAttack': 1,
            'GuerrillaProb': 100,
            'RangedPosMinDis': 5,
            'RangedPosMaxDis': 7,
            'RangedPosMinAngle': 90,
            'RangedPosMaxAngle': 105,
            'RangedPosR': 20,
            'HideR': 10,
            'HideTime': 200,
            'HideAttackStandingTime': 100,
            'FuzzyInterval': 200,
            'FuzzyProb': 100 },
        PARAM_LEVEL_MEDIUM_HIGH: {
            'GuerrillaInterval': 200,
            'GuerrillaAttack': 1,
            'GuerrillaProb': 100,
            'RangedPosMinDis': 4,
            'RangedPosMaxDis': 6,
            'RangedPosMinAngle': 75,
            'RangedPosMaxAngle': 105,
            'RangedPosR': 15,
            'HideR': 10,
            'HideTime': 200,
            'HideAttackStandingTime': 100,
            'FuzzyInterval': 200,
            'FuzzyProb': 100 },
        PARAM_LEVEL_CLOSE_LOW: {
            'GuerrillaInterval': 400,
            'GuerrillaAttack': 1,
            'GuerrillaProb': 50,
            'RangedPosMinDis': 3,
            'RangedPosMaxDis': 5,
            'RangedPosMinAngle': 75,
            'RangedPosMaxAngle': 105,
            'RangedPosR': 10,
            'HideR': 10,
            'HideTime': 400,
            'HideAttackStandingTime': 100,
            'FuzzyInterval': 400,
            'FuzzyProb': 50 } } }

def GetAIConfParam(iAIType, iAILevel):
    if iAIType in (MONSTERAI_TYPE_GUARDIAN, MONSTERAI_TYPE_AREAMOVE):
        return { }
    if iAIType == MONSTERAI_TYPE_HATESEARCH:
        return g_AITempParam[iAIType][iAILevel]
    if iAILevel not in g_AITempParam[MONSTERAI_TYPE_DEFAULT]:
        iAILevel = PARAM_LEVEL_CLOSE_LOW
    return g_AITempParam[MONSTERAI_TYPE_DEFAULT][iAILevel]

