# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_cscommondef/cs_fight.pyc
# RelativePath: clientlogic/cl_cscommondef/cs_fight.pyc
# Source Generated with Decompyle++
# File: cs_fight.pyc (Python 3.6)

SCENEOBJ_TYPE = 2146435072
WARRIOR_HERO = 536870912
WARRIOR_BUILD = 268435456
WARRIOR_MONSTER = 134217728
WARRIOR_SUMMON = 67108864
NWARRIOR_VIRTUAL = 1073741824
NWARRIOR_NPC = 33554432
NWARRIOR_DROP = 16777216
WARRIOR_SERVANT = 1048576
WARRIOR_DEVICE = 2097152
WARRIOR_PET = 4194304
WARRIOR_MASK = WARRIOR_HERO | WARRIOR_BUILD | WARRIOR_MONSTER | WARRIOR_SUMMON | WARRIOR_DEVICE | WARRIOR_SERVANT | WARRIOR_PET
CTRLWARRIOR_MASK = WARRIOR_HERO | WARRIOR_MONSTER | WARRIOR_SERVANT | WARRIOR_PET
NWARRIOR_MASK = NWARRIOR_DROP | NWARRIOR_NPC | NWARRIOR_VIRTUAL
WARRIOR_FAKER_HERO = WARRIOR_HERO | 1
BUILD_TYPE_MASK = WARRIOR_BUILD | 3840
WARRIOR_OBSTACLE = WARRIOR_BUILD | 256
WARRIOR_BUILD_TRAP = WARRIOR_BUILD | 512
WARRIOR_SPECIAL = WARRIOR_BUILD | 1024
WARRIOR_PROTEGE = WARRIOR_BUILD | 2048
WARRIOR_OBSTACLE_NORMAL = WARRIOR_OBSTACLE | 1
WARRIOR_OBSTACLE_CTRLGATE = WARRIOR_OBSTACLE | 2
WARRIOR_OBSTACLE_BUNKER = WARRIOR_OBSTACLE | 3
WARRIOR_OBSTACLE_VICCTRL = WARRIOR_OBSTACLE | 4
WARRIOR_OBSTACLE_SIMCTRL = WARRIOR_OBSTACLE | 5
WARRIOR_OBSTACLE_TRANGATE = WARRIOR_OBSTACLE | 6
WARRIOR_OBSTACLE_TRIDESTROY = WARRIOR_OBSTACLE | 7
WARRIOR_OBSTACLE_STATICTRAN = WARRIOR_OBSTACLE | 8
WARRIOR_OBSTACLE_SLIDEDOOR = WARRIOR_OBSTACLE | 9
WARRIOR_OBSTACLE_BROKENPILLAR = WARRIOR_OBSTACLE | 16
WARRIOR_OBSTACLE_LVTRIDESTORY = WARRIOR_OBSTACLE | 17
WARRIOR_OBSTACLE_HINDER = WARRIOR_OBSTACLE | 18
WARRIOR_TRAP_NORMAL = WARRIOR_BUILD_TRAP | 1
WARRIOR_TRAP_STONE = WARRIOR_BUILD_TRAP | 2
WARRIOR_TRAP_SMASH = WARRIOR_BUILD_TRAP | 3
WARRIOR_TRAP_UPSTONE = WARRIOR_BUILD_TRAP | 4
WARRIOR_TRAP_ROTATEPILLAR = WARRIOR_BUILD_TRAP | 5
WARRIOR_TRAP_VENT = WARRIOR_BUILD_TRAP | 6
WARRIOR_TRAP_MOVEPLANE = WARRIOR_BUILD_TRAP | 7
WARRIOR_TRAP_FAKERPLANK = WARRIOR_BUILD_TRAP | 8
WARRIOR_TRAP_THUNDERBUCKET = WARRIOR_BUILD_TRAP | 9
WARRIOR_AIRWALL_PHY = WARRIOR_SPECIAL | 1
WARRIOR_STONEPILLAR = WARRIOR_SPECIAL | 2
WARRIOR_PERFORM_BUILD = WARRIOR_SPECIAL | 3
WARRIOR_LUOHOU_PILLAR = WARRIOR_SPECIAL | 4
WARRIOR_SUMMON_STELE = WARRIOR_SPECIAL | 5
WARRIOR_MONSTERBUILD = WARRIOR_SPECIAL | 6
WARRIOR_GEYSER = WARRIOR_SPECIAL | 7
WARRIOR_MONSTERHINDER = WARRIOR_SPECIAL | 8
WARRIOR_MONSTENOPHYRHINDER = WARRIOR_SPECIAL | 9
WARRIOR_MOVEBUILD = WARRIOR_SPECIAL | 16
WARRIOR_PROTEGE_NORMAL = WARRIOR_PROTEGE | 1
MONSTER_TYPE_MASK = WARRIOR_MONSTER | 61440
WARRIOR_NORMAL = WARRIOR_MONSTER | 4096
WARRIOR_ELITE = WARRIOR_MONSTER | 8192
WARRIOR_BOSS = WARRIOR_MONSTER | 16384
MONSTER_CLASSIFY_MASK = 255
MONSTER_CLASSIFY_BADGER = 1
MONSTER_CLASSIFY_SMANEAR = 2
MONSTER_CLASSIFY_SMAFAR = 3
MONSTER_CLASSIFY_MEDNEAR = 4
MONSTER_CLASSIFY_MEDFAR = 5
MONSTER_CLASSIFY_HEVNEAR = 6
MONSTER_CLASSIFY_HEVFAR = 7
MONSTER_CLASSIFY_THROW = 8
MONSTER_CLASSIFY_SNIPE = 9
MONSTER_CLASSIFY_MAGIC = 10
MONSTER_CLASSIFY_FOOT = 11
MONSTER_CLASSIFY_FLY = 12
MONSTER_CLASSIFY_BOSS = 13
MONSTER_CLASSIFY_DART = 15
MONSTER_CLASSIFY_BATTERY = 16
MONSTER_CLASSIFY_PETROCHEMICAL = 17
MONSTER_CLASSIFY_BOXMONSTER = 18
MONSTER_CLASSIFY_LARGESUMMON = 19
MONSTER_CLASSIFY_RIDE = 20
MONSTER_CLASSIFY_CANNONFODDER = 21
MONSTER_CLASSIFY_PART = 22
MONSTER_CLASSIFY_DURABILITY = 23
MONSTER_CLASSIFY_ONELAYER_FLY = 32
MONSTER_CLASSIFY_ONELAYER_SMANEAR = 33
MONSTER_CLASSIFY_ONELAYER_MEDNEAR = 34
MONSTER_CLASSIFY_TWOLAYER_BADGER = 80
MONSTER_CLASSIFY_TWOLAYER_BATTERY = 81
MONSTER_CLASSIFY_TWOLAYER_SMANEAR = 82
MONSTER_CLASSIFY_TWOLAYER_HEVNEAR = 83
MONSTER_CLASSIFY_TWOLAYER_MEDFAR = 84
MONSTER_CLASSIFY_TWOLAYER_MEDNEAR = 85
MONSTER_CLASSIFY_TWOLAYER_HEVFAR = 86
MONSTER_CLASSIFY_THREELAYER_SMAFAR = 96
MONSTER_CLASSIFY_THREELAYER_MEDFAR = 97
MONSTER_CLASSIFY_THREELAYER_HEVFAR = 98
MONSTER_CLASSIFY_THREELAYER_MEDNEAR = 99
MONSTER_CLASSIFY_THREELAYER_FOOT = 100
MONSTER_CLASSIFY_THREELAYER_HEVNEAR = 101
MONSTER_CLASSIFY_THREELAYER_MAGIC = 102
WARRIOR_NORBADGER = WARRIOR_NORMAL | MONSTER_CLASSIFY_BADGER
WARRIOR_NORSMANEAR = WARRIOR_NORMAL | MONSTER_CLASSIFY_SMANEAR
WARRIOR_NORSMAFAR = WARRIOR_NORMAL | MONSTER_CLASSIFY_SMAFAR
WARRIOR_NORMEDNEAR = WARRIOR_NORMAL | MONSTER_CLASSIFY_MEDNEAR
WARRIOR_NORMEDFAR = WARRIOR_NORMAL | MONSTER_CLASSIFY_MEDFAR
WARRIOR_NORHEVNEAR = WARRIOR_NORMAL | MONSTER_CLASSIFY_HEVNEAR
WARRIOR_NORHEVFAR = WARRIOR_NORMAL | MONSTER_CLASSIFY_HEVFAR
WARRIOR_NORTHROW = WARRIOR_NORMAL | MONSTER_CLASSIFY_THROW
WARRIOR_NORSNIPE = WARRIOR_NORMAL | MONSTER_CLASSIFY_SNIPE
WARRIOR_NORMAGIC = WARRIOR_NORMAL | MONSTER_CLASSIFY_MAGIC
WARRIOR_NORFOOT = WARRIOR_NORMAL | MONSTER_CLASSIFY_FOOT
WARRIOR_NORFLY = WARRIOR_NORMAL | MONSTER_CLASSIFY_FLY
WARRIOR_NORDART = WARRIOR_NORMAL | MONSTER_CLASSIFY_DART
WARRIOR_NORBATTERY = WARRIOR_NORMAL | MONSTER_CLASSIFY_BATTERY
WARRIOR_NORPETRO = WARRIOR_NORMAL | MONSTER_CLASSIFY_PETROCHEMICAL
WARRIOR_NORBOX = WARRIOR_NORMAL | MONSTER_CLASSIFY_BOXMONSTER
WARRIOR_NORLARGESUMMON = WARRIOR_NORMAL | MONSTER_CLASSIFY_LARGESUMMON
WARRIOR_NORRIDE = WARRIOR_NORMAL | MONSTER_CLASSIFY_RIDE
WARRIOR_NORCANNONFODDER = WARRIOR_NORMAL | MONSTER_CLASSIFY_CANNONFODDER
WARRIOR_NORPART = WARRIOR_NORMAL | MONSTER_CLASSIFY_PART
WARRIOR_NODURABILITY = WARRIOR_NORMAL | MONSTER_CLASSIFY_DURABILITY
WARRIOR_ELIBADGER = WARRIOR_ELITE | MONSTER_CLASSIFY_BADGER
WARRIOR_ELISMANEAR = WARRIOR_ELITE | MONSTER_CLASSIFY_SMANEAR
WARRIOR_ELISMAFAR = WARRIOR_ELITE | MONSTER_CLASSIFY_SMAFAR
WARRIOR_ELIMEDNEAR = WARRIOR_ELITE | MONSTER_CLASSIFY_MEDNEAR
WARRIOR_ELIMEDFAR = WARRIOR_ELITE | MONSTER_CLASSIFY_MEDFAR
WARRIOR_ELIHEVNEAR = WARRIOR_ELITE | MONSTER_CLASSIFY_HEVNEAR
WARRIOR_ELIHEVFAR = WARRIOR_ELITE | MONSTER_CLASSIFY_HEVFAR
WARRIOR_ELITHROW = WARRIOR_ELITE | MONSTER_CLASSIFY_THROW
WARRIOR_ELISNIPE = WARRIOR_ELITE | MONSTER_CLASSIFY_SNIPE
WARRIOR_ELIMAGIC = WARRIOR_ELITE | MONSTER_CLASSIFY_MAGIC
WARRIOR_ELIFOOT = WARRIOR_ELITE | MONSTER_CLASSIFY_FOOT
WARRIOR_ELIDART = WARRIOR_ELITE | MONSTER_CLASSIFY_DART
WARRIOR_ELIBATTERY = WARRIOR_ELITE | MONSTER_CLASSIFY_BATTERY
WARRIOR_ELIPETRO = WARRIOR_ELITE | MONSTER_CLASSIFY_PETROCHEMICAL
WARRIOR_ELIBOX = WARRIOR_ELITE | MONSTER_CLASSIFY_BOXMONSTER
WARRIOR_ELIRIDE = WARRIOR_ELITE | MONSTER_CLASSIFY_RIDE
WARRIOR_ELICANNONFODDER = WARRIOR_ELITE | MONSTER_CLASSIFY_CANNONFODDER
WARRIOR_ELIPART = WARRIOR_ELITE | MONSTER_CLASSIFY_PART
WARRIOR_BOSSSTAT = WARRIOR_BOSS | 256 | MONSTER_CLASSIFY_BOSS
WARRIOR_BOSSDM = WARRIOR_BOSS | 512 | MONSTER_CLASSIFY_BOSS
WARRIOR_BOSSCANNON = WARRIOR_BOSS | 1024 | MONSTER_CLASSIFY_BOSS
WARRIOR_BOSSKING = WARRIOR_BOSS | 2048 | MONSTER_CLASSIFY_BOSS
BOSS_DONOT_COUNT = (WARRIOR_BOSSCANNON,)
PART_TYPE = (WARRIOR_BOSSCANNON,)
WARRIOR_GRENADE = WARRIOR_SUMMON | 1
WARRIOR_ENTITYEFFECT = WARRIOR_SUMMON | 2
WARRIOR_PERFORM = WARRIOR_SUMMON | 3
WARRIOR_SUMMON_BUILD = WARRIOR_SUMMON | 4
WARRIOR_CIRCLE = WARRIOR_SUMMON | 5
WARRIOR_BODYPART = WARRIOR_SUMMON | 6
WARRIOR_INKWALL = WARRIOR_SUMMON | 7
WARRIOR_BEACON = WARRIOR_SUMMON | 8
WARRIOR_INCUBATOR = WARRIOR_SUMMON | 9
WARRIOR_MONSTERBEACON = WARRIOR_SUMMON | 10
WARRIOR_MOVEEFFECT = WARRIOR_SUMMON | 11
WARRIOR_PHYSXENTITYEFFECT = WARRIOR_SUMMON | 12
WARRIOR_BARRIER = WARRIOR_SUMMON | 13
WARRIOR_SCENEQUERY_ENTITYEFFECT = WARRIOR_SUMMON | 14
WARRIOR_NOPHYSMOVEEFFECT = WARRIOR_SUMMON | 15
WARRIOR_SUMMON_BARRIER = WARRIOR_SUMMON | 16
WARRIOR_SUMMON_SEED = WARRIOR_SUMMON | 17
WARRIOR_SUMMON_AIRFOLLOWEFFECT = WARRIOR_SUMMON | 18
WARRIOR_MECH = WARRIOR_SERVANT | 1
WARRIOR_PLANT = WARRIOR_SERVANT | 2
WARRIOR_SPARE = WARRIOR_SERVANT | 3
WARRIOR_PET_MINI = WARRIOR_PET | 1
WARRIOR_PET_MINICLONE = WARRIOR_PET | 2
WARRIOR_PET_HEROSIDE = WARRIOR_PET | 3
WARRIOR_DEVICE_POISON = WARRIOR_DEVICE | 1
WARRIOR_DEVICE_TURRET = WARRIOR_DEVICE | 2
WARRIOR_DEVICE_BARRIER = WARRIOR_DEVICE | 3
NWARRIOR_DROP_EQUIP = NWARRIOR_DROP | 1
NWARRIOR_DROP_BULLET = NWARRIOR_DROP | 3
NWARRIOR_DROP_CASH = NWARRIOR_DROP | 4
NWARRIOR_DROP_RELIC = NWARRIOR_DROP | 5
NWARRIOR_DROP_TRIGGER = NWARRIOR_DROP | 6
NWARRIOR_DROP_KEY = NWARRIOR_DROP | 7
NWARRIOR_DROP_GSCASH = NWARRIOR_DROP | 9
NWARRIOR_DROP_KEYITEM = NWARRIOR_DROP | 10
NWARRIOR_DROP_RELIC_CURSE = NWARRIOR_DROP | 11
NWARRIOR_DROP_TREASURE_DEAD = NWARRIOR_DROP | 12
NWARRIOR_DROP_DEMON = NWARRIOR_DROP | 13
NWARRIOR_DROP_RELIFE = NWARRIOR_DROP | 14
NWARRIOR_DROP_EXPERIENCE = NWARRIOR_DROP | 15
NWARRIOR_DROP_RAREITEM = NWARRIOR_DROP | 16
NWARRIOR_DROP_AXE = NWARRIOR_DROP | 17
NWARRIOR_DROP_ENCHANTING_BULLET = NWARRIOR_DROP | 18
NWARRIOR_DROP_MAGIC_POWER = NWARRIOR_DROP | 19
NWARRIOR_DROP_INKBEAD = NWARRIOR_DROP | 20
NWARRIOR_DROP_DEVICECOMP = NWARRIOR_DROP | 21
NWARRIOR_DROP_PETEGG = NWARRIOR_DROP | 22
NWARRIOR_DROP_RELIC_BLANK = NWARRIOR_DROP | 23
NWARRIOR_DROP_RELIC_MYSTERY = NWARRIOR_DROP | 24
NWARRIOR_DROP_MAGIC_WAND = NWARRIOR_DROP | 25
NWARRIOR_DROP_WANDCOMP = NWARRIOR_DROP | 26
NWARRIOR_DROP_NODISTANCEBULLET = NWARRIOR_DROP | 27
NWARRIOR_DROP_DICE = NWARRIOR_DROP | 28
NWARRIOR_DROP_COOKIES = NWARRIOR_DROP | 29
NWARRIOR_DROP_DICESELECTIONPACKET = NWARRIOR_DROP | 30
NWARRIOR_DROP_DICESPECIALITEM = NWARRIOR_DROP | 31
NWARRIOR_DROP_S7MODULE = NWARRIOR_DROP | 32
NWARRIOR_DROP_S7CRYSTAL = NWARRIOR_DROP | 33
NWARRIOR_DROP_SUMMONSOUL = NWARRIOR_DROP | 34
NWARRIOR_DROP_S8THIRDITEM = NWARRIOR_DROP | 35
NWARRIOR_DROP_S8GEMITEM = NWARRIOR_DROP | 36
NWARRIOR_NPC_ITEMBOX = NWARRIOR_NPC | 1
NWARRIOR_NPC_TRANSFER = NWARRIOR_NPC | 2
NWARRIOR_NPC_SHOP = NWARRIOR_NPC | 3
NWARRIOR_NPC_PASSBOX = NWARRIOR_NPC | 4
NWARRIOR_NPC_GOLDENCUP = NWARRIOR_NPC | 5
NWARRIOR_NPC_LOCKEDBOX = NWARRIOR_NPC | 6
NWARRIOR_NPC_SMITH = NWARRIOR_NPC | 7
NWARRIOR_NPC_MAGICBOX = NWARRIOR_NPC | 8
NWARRIOR_NPC_EVENT = NWARRIOR_NPC | 9
NWARRIOR_NPC_BONFIRE = NWARRIOR_NPC | 11
NWARRIOR_NPC_INITBOX = NWARRIOR_NPC | 12
NWARRIOR_NPC_ELEVATOR = NWARRIOR_NPC | 13
NWARRIOR_NPC_CAR = NWARRIOR_NPC | 14
NWARRIOR_NPC_CANNON = NWARRIOR_NPC | 15
NWARRIOR_NPC_REFRESH = NWARRIOR_NPC | 16
NWARRIOR_NPC_ROOMCHALLENGE = NWARRIOR_NPC | 17
NWARRIOR_NPC_BENEDICTION = NWARRIOR_NPC | 18
NWARRIOR_NPC_GSCASHSHOP = NWARRIOR_NPC | 19
NWARRIOR_NPC_TRANSFERPOS = NWARRIOR_NPC | 20
NWARRIOR_NPC_LIMITGOLDENCUP = NWARRIOR_NPC | 21
NWARRIOR_NPC_CONNECTTRANSFER = NWARRIOR_NPC | 22
NWARRIOR_NPC_RAREGOLDENCUP = NWARRIOR_NPC | 23
NWARRIOR_NPC_RELIC = NWARRIOR_NPC | 24
NWARRIOR_NPC_WEAPONSTORE = NWARRIOR_NPC | 25
NWARRIOR_NPC_PHASESHOP = NWARRIOR_NPC | 32
NWARRIOR_NPC_PHASESMITH = NWARRIOR_NPC | 33
NWARRIOR_NPC_PHASEGOLDENCUP = NWARRIOR_NPC | 34
NWARRIOR_NPC_TASKNPC = NWARRIOR_NPC | 35
NWARRIOR_NPC_EXCHANGEGOLDENCUP = NWARRIOR_NPC | 36
NWARRIOR_NPC_HOOKROPE = NWARRIOR_NPC | 37
NWARRIOR_NPC_PETSHOP = NWARRIOR_NPC | 38
NWARRIOR_NPC_RELICROLLBOX = NWARRIOR_NPC | 39
NWARRIOR_NPC_RELICLOTTERY = NWARRIOR_NPC | 40
NWARRIOR_NPC_WANDSHOP = NWARRIOR_NPC | 41
NWARRIOR_NPC_DICESHOP = NWARRIOR_NPC | 42
NWARRIOR_NPC_S7SHOP = NWARRIOR_NPC | 43
NWARRIOR_NPC_S8SHOP = NWARRIOR_NPC | 44
NWARRIOR_NPC_ALL_GOLDENCUP = {
    NWARRIOR_NPC_GOLDENCUP,
    NWARRIOR_NPC_LIMITGOLDENCUP,
    NWARRIOR_NPC_RAREGOLDENCUP,
    NWARRIOR_NPC_PHASEGOLDENCUP,
    NWARRIOR_NPC_EXCHANGEGOLDENCUP}
NWARRIOR_VIRTUAL_DYNCEVENT = NWARRIOR_VIRTUAL | 256
NWARRIOR_VIRTUAL_REALBULLET = NWARRIOR_VIRTUAL | 512
OBJ_SELF_DEF = 4
OBJ_TEAMMATE_DEF = 2
OBJ_ENEMY_DEF = 1
OBJ_SELF = OBJ_SELF_DEF | WARRIOR_MASK
OBJ_FRIEND = OBJ_SELF_DEF | OBJ_TEAMMATE_DEF | WARRIOR_MASK
OBJ_FRIEND_NOSELF = OBJ_TEAMMATE_DEF | WARRIOR_MASK
OBJ_FRIEND_HERO = OBJ_SELF_DEF | OBJ_TEAMMATE_DEF | WARRIOR_HERO
OBJ_FRIEND_HERONOSELF = OBJ_TEAMMATE_DEF | WARRIOR_HERO
OBJ_ENEMY = OBJ_ENEMY_DEF | WARRIOR_MASK
OBJ_ALL = OBJ_SELF_DEF | OBJ_TEAMMATE_DEF | OBJ_ENEMY_DEF | WARRIOR_MASK
OBJ_ALL_NOSELF = OBJ_TEAMMATE_DEF | OBJ_ENEMY_DEF | WARRIOR_MASK
OBJ_ALL_PLAYER = WARRIOR_HERO | WARRIOR_SERVANT | WARRIOR_DEVICE | WARRIOR_PET
OBJ_NOSELF = OBJ_ALL_NOSELF
OBJ_ALLNOSELF = OBJ_ALL_NOSELF
OBJ_ATTTYPEMASK = 3
OBJ_ATTACK = 1
OBJ_VICTIM = 2
CURE_MASK_SRC = 0xFF000000
CURE_TYPE_PERFORM = 268435456
CURE_TYPE_SCENE = 536870912
DAM_MASK_SRC = 16711680
DAM_MASK_CLASS = 15728640
DAM_TYPE_WEAPON = 8388608
DAM_TYPE_PERFORM = 4194304
DAM_TYPE_PERSISTENCE = 2097152
DAM_TYPE_SCENE = 1048576
DAM_TYPE_BLEED = DAM_TYPE_PERSISTENCE | 65536
DAM_TYPE_BURN = DAM_TYPE_PERSISTENCE | 131072
DAM_USE_ALL = 57344
DAM_USE_SHIELD = 32768
DAM_USE_ARMOR = 16384
DAM_USE_HP = 8192
DAM_IGNORE_SHIELD = DAM_USE_ARMOR | DAM_USE_HP
DAM_IGNORE_ARMOR = DAM_USE_SHIELD | DAM_USE_HP
DAM_IGNORE_HP = DAM_USE_SHIELD | DAM_USE_ARMOR
DAM_MASK_ELEMENT = 7936
DAM_TYPE_TRUE = 4096
DAM_TYPE_NORMAL = 2048
DAM_TYPE_FIRE = 1024
DAM_TYPE_CORRISION = 512
DAM_TYPE_THUNDER = 256
DAM_TYPE_ELEMENT = DAM_TYPE_FIRE | DAM_TYPE_CORRISION | DAM_TYPE_THUNDER
DAM_MASK_SIDE = 240
DAM_TYPE_FRIEND = 16
DAM_TYPE_ENEMY = 32
PARTMOVE = 4
DAM_MASK_PART = 15
DAM_TYPE_WEAKNESS = 1
DAM_TYPE_AREA = 2
DAM_TYPE_SHIELD = 4
DAM_TYPE_HARDNESS = 8
MAF_TYPE_FIRE = 1
MAF_TYPE_CORRISION = 2
MAF_TYPE_THUNDER = 4
MAF_TYPE_DEFEND = 8
MAF_TYPE_CLEANSE = 16
MAF_TYPE_UNYIELD = 32
MAF_TYPE_IMMORTAL = 64
MAF_TYPE_CURE = 128
MAF_TYPE_SEASONWAND = 256
DEFEND_TREND_NONE = 0
DEFEND_TREND_SHIELD = 1
DEFEND_TREND_ARMOR = 2
CAREER_GENERAL = 150
DROP_REASON_NORMAL = 0
DROP_REASON_UNLOCK = 1
DROP_REASON_NPCREWARD = 2
DROP_REASON_NPCMARK = 3
DROP_REASON_WEAPONMARK = 4
DROP_REASON_DEVICECOMPONENT = 5
DROP_REASON_MONSTERRELIC = 6
DROP_REASON_DISCARDRELIC = 7
DROP_REASON_GAMBLER_ROLLRELIC = 8
MONSTER_STATUS_DEFAULT = 1
MONSTER_STATUS_ATTACK = 2
STATUS_DEFAULT = 0
STATUS_PATROL = 1
STATUS_RUN = 2
STATUS_SPRINT = 3
SNIPE_STATUS_CLOSE = 1
SNIPE_STATUS_OPEN = 2
STATUS_STOP = 1
STATUS_MOVE = 2
STATUS_JUMP = 3
STATUS_SERVSTOP = 4
STATUS_WINK = 5
STATUS_PUSH = 6
STATUS_DASH = 7
STATUS_LINE = 8
STATUS_AIRLINE = 9
STATUS_AIRSTOP = 10
STATUS_AIRCURVE = 11
STATUS_HOOKROPE = 12
STATUS_GLIDE = 13
STATUS_GEYSER = 14
STATYS_FLY = 16
FORBID_ATTACK = 1001
FORBID_FILLBULLET = 1002
FORBID_SWITCHWEAPON = 1004
FORBID_USEDRUG = 1005
FORBID_MOVE = 1006
FORBID_OPENSNIPE = 1007
FORBID_OPACTION = 1008
FORBID_THROW = 1010
FORBID_JUMP = 1011
FORBID_SAVE = 1012
FORBID_USECAREERPF = 1013
FORBID_WEAPONATIVE = 1014
FORBID_PUSHED = 1015
FORBID_SHIELDRECOVER = 1016
FORBID_ROTATE = 1017
FORBID_MONSTERPF = 1018
FORBID_MINOR = 1019
FORBID_BREAKSHIELDRECOVER = 1020
FORBID_SHIELDCURE = 1021
FORBID_UNIONPF = 1022
FORBID_SWITCHWEAPONATTPF = 1023
FORBID_OPENPACKAGEPANEL = 1024
FORBID_DROPWEAPON = 1025
FORBID_RECYCLE = 1026
FORBID_FOCUS = 1027
FORBID_OPSKILL = 1028
FORBID_SERVANT_SWITCH = 1029
FORBID_AUTO_FILLBULLET = 1030
FORBID_SWITCHOVER_DEVICE = 1031
FORBID_DEVICE_ACTIVE = 1032
FORBID_DASH = 1033
FORBID_AUTO_ATTACK = 1034
FORBID_DEVICE_OPEN = 1035
FORBID_NONE = 1036
OP_MOVE = 1
OP_JUMP = 2
OP_WINK = 3
OP_FALL = 4
OP_STOP = 5
LEVEL_STATUS_WAIT = 1
LEVEL_STATUS_START = 2
LEVEL_STATUS_GOAL = 3
LEVEL_STATUS_FINISH = 4
LEVEL_TYPE_NONE = 0
LEVEL_TYPE_HALL = 1
LEVEL_TYPE_FIGHT = 2
LEVEL_TYPE_HIDE = 3
LEVEL_TYPE_BOSS = 4
LEVEL_DIFF_NORMAL = 1
LEVEL_DIFF_MEDIUM = 2
LEVEL_DIFF_HARD = 3
HIDELV_TYPE_NORMAL = 1
HIDELV_TYPE_DEFEND = 2
HIDELV_TYPE_ELITE = 3
HIDELV_TYPE_SIGHT = 4
HIDELV_TYPE_TRAP = 5
HIDELV_TYPE_JUMP = 6
HIDELV_TYPE_PETROCHEMICAL = 7
HIDELV_TYPE_CASH = 8
GAMETYPE_NONE = 0
GAMETYPE_DESTROY = 1
GAMETYPE_DEFENSE = 2
GAMETYPE_ASSASSINATE = 3
GAMETYPE_CONVOY = 4
GAMETYPE_LIMITLIVE = 5
GAMETYPE_MACHINE = 6
GAMETYPE_DEFEND = 7
GAMETYPE_LIMITDEFEND = 8
GAMETYPE_JUMP = 9
QIANLONG_TYPE_CASH = 1
QIANLONG_TYPE_BOXMONSTER = 2
QIANLONG_TYPE_KILLBOXMONSTER = 3
LINE_LOCTYPE_NORMAL = 0
LINE_LOCTYPE_ORIGIN = 1
LINE_LOCTYPE_END = 2
LINE_LOCTYPE_ORIEND = LINE_LOCTYPE_ORIGIN | LINE_LOCTYPE_END
LEVEL_NOTIFY_START = 1
LEVEL_NOTIFY_GOAL = 2
LAYER_CHOOSE_HIDE = 1
LAYER_CHOOSE_ELE = 2
LAYER_CHOOSE_CHALLENGE = 3
LAYER_CHOOSE_EVENTNPC = 4
LAYER_CHOOSE_SHOP = 5
LAYER_CHOOSE_CRAFTSMAN = 6
LAYER_CHOOSE_GSCASHSHOP = 7
LAYER_CHOOSE_TASKNPC = 8
LAYER_CHOOSE_PETSHOP = 9
LAYER_CHOOSE_REGROUPRELIC = 10
LAYER_CHOOSE_RELICLOTTERY = 11
LAYER_CHOOSE_WANDSHOP = 12
LAYER_CHOOSE_DICESHOP = 13
LAYER_CHOOSE_S7SHOP = 14
LAYER_CHOOSE_S8SHOP = 15
SCMOD_PROTALIN = 1
SCMOD_MONSTER = 2
SCMOD_TRAP = 3
SCMOD_NPC = 4
SCMOD_PROPS = 5
SCMOD_DROP = 6
SCMOD_MANAGER = 7
SCMOD_ROOMNODE = 8
SCMOD_PFPOS = 9
HP_TYPE_NORMAL = 1
HP_TYPE_ARMOR = 2
HP_TYPE_SHIELD = 4
g_ElementFactor = {
    DAM_TYPE_THUNDER: {
        HP_TYPE_SHIELD: 15000,
        HP_TYPE_ARMOR: 7500,
        HP_TYPE_NORMAL: 7500 },
    DAM_TYPE_CORRISION: {
        HP_TYPE_SHIELD: 7500,
        HP_TYPE_ARMOR: 15000,
        HP_TYPE_NORMAL: 7500 },
    DAM_TYPE_FIRE: {
        HP_TYPE_SHIELD: 7500,
        HP_TYPE_ARMOR: 7500,
        HP_TYPE_NORMAL: 15000 },
    DAM_TYPE_NORMAL: {
        HP_TYPE_SHIELD: 10000,
        HP_TYPE_ARMOR: 7500,
        HP_TYPE_NORMAL: 10000 } }
g_PositiveElement = {
    HP_TYPE_SHIELD: DAM_TYPE_THUNDER,
    HP_TYPE_ARMOR: DAM_TYPE_CORRISION,
    HP_TYPE_NORMAL: DAM_TYPE_FIRE }

def GetElementFactor(iDamType, lstExtraElement, iHPType):
    iDamType = iDamType & DAM_MASK_ELEMENT
    if iDamType in g_ElementFactor and iHPType in g_ElementFactor[iDamType]:
        iFactor = g_ElementFactor[iDamType][iHPType]
    else:
        iFactor = 10000
    for iExtraType in lstExtraElement:
        if iExtraType in g_ElementFactor and iHPType in g_ElementFactor[iExtraType]:
            iExtraFactor = g_ElementFactor[iExtraType][iHPType]
            if iExtraFactor > iFactor:
                iFactor = iExtraFactor
    
    return iFactor

g_Attr2HPType = {
    'HP': HP_TYPE_NORMAL,
    'Shield': HP_TYPE_SHIELD,
    'Armor': HP_TYPE_ARMOR }
g_ElementDefAttrKey = {
    DAM_TYPE_THUNDER: 'DefThunder',
    DAM_TYPE_CORRISION: 'DefCorrision',
    DAM_TYPE_FIRE: 'DefFire',
    DAM_TYPE_NORMAL: 'DefPhysical' }
NPC_ACTION_NONE = 0
NPC_ACTION_ITEMBOX = 1
NPC_ACTION_MAPCHOOSE = 2
NPC_ACTION_SHOP = 3
NPC_ACTION_SETTLELEVEL = 4
NPC_ACTION_SELECTBENE = 5
NPC_ACTION_REPLACEBENE = 6
NPC_CB_LIST = 0
NPC_CB_VALUE = 1
NPC_CB_ITEM = 2
NPC_CB_DICT = 3
NPC_CB_VALUELIST = 4
NPC_CB_REFRESH = 5
NPC_CB_ITEMCONOP = 6
NPC_CB_CHOOSEALL = 7
NPC_CB_INJECT = 8
NPC_CAT_PHASE_INIT = 0
NPC_CAT_PHASE_ING = 1
NPC_CAT_PHASE_SUC = 2
NPC_CAT_PHASE_FAIL = 4
MONSTER_PART_UNTAGGED = 1
MONSTER_PART_WEAKNESS = 2
MONSTER_PART_UPPERLEFT = 3
MONSTER_PART_UPPERRIGHT = 4
MONSTER_PART_UPPERBODY = 5
MONSTER_PART_UNDERLEFT = 6
MONSTER_PART_UNDERRIGHT = 7
MONSTER_PART_SHIELD = 8
MONSTER_PART_EXPLOSIVE = 9
MONSTER_PART_ELBOWLEFT = 10
MONSTER_PART_ELBOWRIGHT = 11
MONSTER_PART_STOMACH = 12
MONSTER_PART_HARDNESS = 13
MONSTER_PART_LEFTGUN = 14
MONSTER_PART_RIGHTGUN = 15
MONSTER_PART_ATTACH = 16
MONSTER_PART_ATTACH_WEAKNESS = 17
MONSTER_PART_ATTACH_HARDNESS = 19
MONSTER_PART_SECKILL = 20
MONSTER_PART_BARRIAR = 21
MONSTER_PART_FLAW = 22
MONSTER_PART_WEAKNESSFLAW = 23
MONSTER_PART_ENERGYSHIELDLEFT = 24
MONSTER_PART_ENERGYSHIELDRIGHT = 25
MONSTER_PART_S6CHALLENGEPFSHIELD = 26
HITPART_DIRECTPOS = 99
MONSERT_PART_ALLWEAKNESS = [
    MONSTER_PART_WEAKNESS,
    MONSTER_PART_ATTACH_WEAKNESS,
    MONSTER_PART_FLAW,
    MONSTER_PART_WEAKNESSFLAW]
g_HitPartToType = {
    MONSTER_PART_S6CHALLENGEPFSHIELD: DAM_TYPE_SHIELD,
    MONSTER_PART_ENERGYSHIELDRIGHT: DAM_TYPE_SHIELD,
    MONSTER_PART_ENERGYSHIELDLEFT: DAM_TYPE_SHIELD,
    MONSTER_PART_WEAKNESSFLAW: DAM_TYPE_WEAKNESS,
    MONSTER_PART_FLAW: DAM_TYPE_WEAKNESS,
    MONSTER_PART_RIGHTGUN: DAM_TYPE_SHIELD,
    MONSTER_PART_LEFTGUN: DAM_TYPE_SHIELD,
    MONSTER_PART_HARDNESS: DAM_TYPE_HARDNESS,
    MONSTER_PART_EXPLOSIVE: DAM_TYPE_SHIELD,
    MONSTER_PART_SHIELD: DAM_TYPE_SHIELD,
    MONSTER_PART_WEAKNESS: DAM_TYPE_WEAKNESS }

def GetGlobalHitPartToType():
    return g_HitPartToType

g_FightType2HitArea = (MONSTER_PART_ATTACH, MONSTER_PART_ATTACH_WEAKNESS, MONSTER_PART_ATTACH_HARDNESS)

def GetContainHitArea(oWarrior):
    return g_FightType2HitArea

SIDE_TYPE_HERO = 1
SIDE_TYPE_MONSTER = 2
SIDE_TYPE_VERTIGO = 4
SIDE_TYPE_OBSTACLE = 8
g_SideTypeTeammateMap = {
    SIDE_TYPE_OBSTACLE: SIDE_TYPE_OBSTACLE,
    SIDE_TYPE_VERTIGO: 0,
    SIDE_TYPE_MONSTER: SIDE_TYPE_MONSTER,
    SIDE_TYPE_HERO: SIDE_TYPE_HERO }
g_SideTypeTeammate = tuple((g_SideTypeTeammateMap.get(x, 0) for x in range(max(g_SideTypeTeammateMap) + 1)))
g_SideTypeEnemyMap = {
    SIDE_TYPE_OBSTACLE: SIDE_TYPE_HERO | SIDE_TYPE_MONSTER | SIDE_TYPE_VERTIGO,
    SIDE_TYPE_VERTIGO: SIDE_TYPE_MONSTER | SIDE_TYPE_VERTIGO | SIDE_TYPE_OBSTACLE,
    SIDE_TYPE_MONSTER: SIDE_TYPE_HERO | SIDE_TYPE_VERTIGO | SIDE_TYPE_OBSTACLE,
    SIDE_TYPE_HERO: SIDE_TYPE_MONSTER | SIDE_TYPE_VERTIGO | SIDE_TYPE_OBSTACLE }
g_SideTypeEnemy = tuple((g_SideTypeEnemyMap.get(x, 0) for x in range(max(g_SideTypeEnemyMap) + 1)))
TYPE_RELIFE_RELIC = 1
TYPE_RELIFE_GSCASH = 2
TYPE_RELIFE_PF = 3
TYPE_RELIFE_PASS = 4
TYPE_RELIFE_GM = 5
TYPE_RELIFE_WARCASH = 6
TYPE_RELIFE_BUY = 7
TYPE_RELIFE_KILLBOSS = 8
TYPE_RELIFE_CHANGE = 9
TYPE_RELIFE_RESCUE = 10
TYPE_RELIFE_PASSIVE = 11
TYPE_RELIFE_TASK = 12
TYPE_RELIFE_RESTPHASE = 13
TYPE_RELIFE_LEAVEBATTLE = 14
TYPE_RELIFE_DICE = 15
TYPE_RELIFE_ALL = (TYPE_RELIFE_RELIC, TYPE_RELIFE_GSCASH, TYPE_RELIFE_PASSIVE, TYPE_RELIFE_TASK, TYPE_RELIFE_DICE)
g_RelifePriority = {
    TYPE_RELIFE_RESTPHASE: 130,
    TYPE_RELIFE_TASK: 120,
    TYPE_RELIFE_RESCUE: 110,
    TYPE_RELIFE_CHANGE: 100,
    TYPE_RELIFE_KILLBOSS: 90,
    TYPE_RELIFE_BUY: 80,
    TYPE_RELIFE_WARCASH: 70,
    TYPE_RELIFE_GM: 60,
    TYPE_RELIFE_PASS: 50,
    TYPE_RELIFE_PF: 40,
    TYPE_RELIFE_GSCASH: 30,
    TYPE_RELIFE_DICE: 21,
    TYPE_RELIFE_PASSIVE: 20,
    TYPE_RELIFE_RELIC: 10 }
DEAD_REAL_DELAYTIME = 500
TAG_RESCUE_NORMAL = 0
TAG_RESCUE_REMOTE = 1
TAG_RESCUE_MECHREMOTE = 2
ABNORMAL_FIRE = 1
ABNORAML_CORRISION = 2
ABNORAML_THUNDER = 4
ELEMENT_MIXTURE_EXPLOSION = 256
ELEMENT_MIXTURE_VERTIGO = 512
ELEMENT_MIXTURE_POISON = 1024
MONSTER_SHOWWAY_DEF = 0
MONSTER_SHOWWAY_DASH = 1
ATTACKERSUBMSG_NORMAL = 1
ATTACKERSUBMSG_BUILD = 2
ATTACKERSUBMSG_SUMMON = 3
SMITHNPCSUBMSG_UPGRADE = 1
SMITHNPCSUBMSG_RECAST = 2
SMITHNPCSUBMSG_ADD_INSCRIPTION = 3
SMITHNPCSUBMSG_RECAST_INSCRIPTION = 4
SMITHNPCSUBMSG_INTERACT = 5
CHANGEWARCASHSUBMSG_ADD = 1
CHANGEWARCASHSUBMSG_COST = 2
PHASE_CHALLENGE_START = 1
PHASE_CHALLENGE_END = 2
PHASE_CHALLENGE_OVER = 3
PHASE_CHALLENGE_PLAYERLEAVE = 4
TREASURERELIC_GENERATELIST = 1
TREASURERELIC_SELECTRELIC = 2
DPSUBMSG_DEFAULT = 1
DPSUBMSG_NOFIRE = 2
PICK_RELIC = 1
PICK_INKBEAD = 2
PICK_SPECIALINKBEAD = 3
PICK_CASH = 4
PICK_BULLET = 5
PICK_S7CRYSTAL = 6
TASK_CREATETASKLIST = 1
TASK_CHOOSETASK = 2
TASK_CHANGESTATUS = 3
TASK_CHOOSEFUN_END = 4
TALENT_CHOOSE_NOMAL = 1
TALENT_CHOOSE_RARE = 2
TALENT_CHOOSE_PHASE = 3
TYPE_RELIC = 1
TYPE_TALENT = 2
TYPE_CHOOSERELIC = 3
TYPE_CHOOSETALENT = 4
TYPE_CREATETALENT = 5
INSCRIPTION_STATE_SEALED = 1
INSCRIPTION_STATE_DISBLE = 2
INSCRIPTION_STATE_SHARE = 3
WUDI_START = 1
WUDI_END = 2
ADD_DEVICE_ENERGY = 1
COST_DEVICE_ENERGY = 2
UNBALANCE_WEAPON = 1
UNBALANCE_OTHER = 2
DEVICE_CONTROL_DEPLOY = 1
DEVICE_CONTROL_RECYCLE = 2
DEVICE_CONTROL_ACTIVE = 3
DEVICE_CONTROL_UNACTIVE = 4
DEVICE_CONTROL_FOLLOW = 5
DEVICE_CONTROL_UNFOLLOW = 6
BLOCK_BY_BARRIER = 1
BLOCK_BY_SUMMON = 2
BLOCK_BY_SERVANT = 3
PET_HATE_START = 1
PET_HATE_UPDATE = 2
PET_HATE_END = 3
FROM_OWNER = 1
FORM_TEAMMATE = 2
CONQUER_CHALLENGE_START = 1
CONQUER_CHALLENGE_REWARD = 2
CONQUER_MONSTER_WEAK_START = 3
CONQUER_MONSTER_WEAK_END = 4
HMS_UP = 1
HMS_Move = 2
HMS_Down = 3
HMS_SlowMove = 4
HMS_Stop = 5
HMS_Charge = 6
HMS_Back = 7
HMS_Jump = 8
HMS_BeatBack = 9
HMS_HookRope = 12
HMS_Geyser = 14
HMS_Fly = 16
CHOOSE_NEAREST = 0
CHOOSE_RANDOM = 1
JUMPFIGURE_KILLMONSTER = 1
JUMPFIGURE_CHALLENGE = 2
JUMPFIGURE_PASSLEVEL = 3
JUMPFIGURE_RELIC = 4
JUMPFIGURE_GOLDEN = 5
JUMPFIGURE_BUYGOODS = 6
JUMPFIGURE_UPGRADEWEAPON = 7
SKILL_TYPE_THROW = 0
SKILL_TYPE_CAREER = 1
OBSTACLE_JAR = 1
OBSTACLE_HIDELEVELDOOR = 2
OBSTACLE_EXPLODE = 3
OBSTACLE_CURVEIGNORE = 4
OBSTACLE_SCENEGOODS = 5
OBSTACLE_FIRE_EXPLODE = 6
OBSTACLE_CORRISION_EXPLODE = 7
OBSTACLE_THUNDER_EXPLODE = 8
OBSTACLE_NORMAL_EXPLODE = 9
NONE_DISTANCE = 0
CLOSE_DISTANCE = 1
MIDDLE_DISTANCE = 2
FAR_DISTANCE = 3
MOVE_CONTINUITY = 1
MOVE_UNIDIRECTION = 2
MOVE_BUILD_LINE = 1
MOVE_BUILD_COMEANDGO = 2
CRT_DEFAULT = 0
CRT_ROTATE_FORATT = 1
CRT_LINELOCK = 2
CURVE_NORMAL = 0
CURVE_RING = 1
CURVE_COMEANDGO = 2
NORMAL = 0
BEZIER = 1
NPC_INTERVAL_REFRESH = 0
NPC_PHASE_REFRESH = 1
NPC_RESIDENT = 2
NPC_NOENTITY_REFRESH = 3
NPC_TYPE_SHOP = 1
NPC_TYPE_CRAFTSMAN = 2
NPC_TYPE_EVENTNPC = 3
NPC_TYPE_CAMEL = 4
NPC_TYPE_UNCLEBAO = 5
NPC_TYPE_GOLDENCUP = 6
LEVEL_STATE_PREPARE = 1
LEVEL_STATE_FIGHT = 2
LEVEL_STATE_FINISH = 3
SURVIVOR_NPC_SHOP = 1063
SURVIVOR_NPC_CRAFTSMAN = 1064
SURVIVOR_NPC_RARECUP = 1067
SURVIVOR_NPC_PHASECUP = 1069
BIGDATA_BOSS_PHASE = 999
CHOOSE_REWARD_CLOSE = 0
CHOOSE_REWARD_OPEN = 1
CHOOSE_REWARD_UPDATE = 2
INTERACT_PROTECT_REWARD = 0
INTERACT_PROTECT_NPC = 1
INTERACT_PROTECT_IGNORETEAM = 2
INTERACT_ALL_TPYE = (INTERACT_PROTECT_REWARD, INTERACT_PROTECT_NPC, INTERACT_PROTECT_IGNORETEAM)
FAKERPLANK_STATUS_DISAPPEAR = 0
FAKERPLANK_STATUS_APPEAR = 1
PLAYER_CHOOSE_GENERAL = 0
PLAYER_CHOOSE_ROLL = 2
PLAYER_CHOOSE_EQUIP = 3
PLAYER_CHOOSEALL_RELIC = 4
PLAYER_CHOOSE_EXTEND = 5
SERVANT_FIGHTTYPE_HUMAN = 1
SERVANT_FIGHTTYPE_TURRET = 2
HATCH_FLAG_NO = 0
HATCH_FLAG_RUNNING = 1
HATCH_FLAG_SUCCESS = 2
HATCH_FLAG_FAIL = 3
SERVANTAGENT_CHOOSE_TARGET_SEE_ENEMY = 1
PET_QUALITY_NORMAL = 1
PET_QUALITY_RARE = 2
PET_TYPE_ALL = 0
PET_TYPE_WIZARD = 1
PET_TYPE_SNIPER = 2
PET_TYPE_WARRIOR = 3
PET_TYPE_SHIELD = 4
PET_TYPE_DEFENSE = 5
PET_TYPE_ELEMENT = 6
PET_TYPE_MINI = 7
PET_TYPE_HEROSIDE = 8
ALL_PET_TYPE = [
    PET_TYPE_ALL,
    PET_TYPE_WIZARD,
    PET_TYPE_SNIPER,
    PET_TYPE_WARRIOR,
    PET_TYPE_SHIELD,
    PET_TYPE_DEFENSE,
    PET_TYPE_ELEMENT,
    PET_TYPE_MINI]
PET_EGG_NORMAL = 1
PET_EGG_RARE = 2
PET_EGG_CANHATCH_NORMAL = 3
PET_EGG_CANHATCH_RARE = 4
DIE_PRIORITY_TYPE_NONE = 0
DIE_PRIORITY_TYPE_DIE = 1
DIE_PRIORITY_TYPE_NO_DIE = 2
DIE_PRIORITY_PF_NO_DIE = 9
DIE_PRIORITY_KILL = 10
DIE_PRIORITY_WEAK = 11
DIE_PRIORITY_CONQUER_SUCC = 12
DIE_PRIORITY_LOCK_BLOOD = 13
DIE_PRIORITY = {
    DIE_PRIORITY_LOCK_BLOOD: DIE_PRIORITY_TYPE_NO_DIE,
    DIE_PRIORITY_CONQUER_SUCC: DIE_PRIORITY_TYPE_DIE,
    DIE_PRIORITY_WEAK: DIE_PRIORITY_TYPE_NO_DIE,
    DIE_PRIORITY_KILL: DIE_PRIORITY_TYPE_DIE,
    DIE_PRIORITY_PF_NO_DIE: DIE_PRIORITY_TYPE_NO_DIE }
COST_BAGBULLET_WEAPON = 1
COST_BAGBULLET_THROW = 2
EXECUTETYPE_ACTIVEPF = 1
EXECUTETYPE_INSCRIPTIONPF = 2
EXECUTETYPE_RELICPF = 4
EXECUTETYPE_DAYTRIALPF = 8
EXECUTETYPE_PART_SECKILL = 16
EXECUTETYPE_PET_ABILITY = 32
EXECUTETYPE_SUIT_EFFECT = 64
EXECUTETYPE_PLANT = 128
MONSTER_DATASID_SEAMONSTERCLONE = 3921
SUIT_HANDLE_ELEMENT = 1
SUIT_HANDLE_INTENSIFY = 2
SUIT_HANDLE_BANRELIC = 3
SUIT_HANDLE_TRIGGERSKILL = 4
SUIT_HANDLE_OPENSUIT = 6
SUIT_HANDLE_CLOSESUIT = 7
SUIT_HANDLE_ROLLTALENT = 8
SUIT_HANDLE_REDUCESUITNUM = 9
SUIT_HANDLE_DAMAGEFACTOR = 10
SUIT_HANDLE_SETTLEACCOUNTSSUIT = 11
SUIT_HANDLE_MYSTERYSUITREWARD = 12
SUIT_HANDLE_TALENT2RELIC = 13
SUIT_HANDLE_COINBANK = 15
SUIT_HANDLE_NOCOSTREROLL = 16
SUIT_HANDLE_SUITBACKRELIC = 17
SUIT_HANDLE_EACHGETWHAT = 18
SUIT_HANDLE_EACHREPLACE = 19
SUIT_HANDLE_REFRESH_WEAPONGRADE = 20
ALL_SUIT_HANDLE = [
    SUIT_HANDLE_ELEMENT,
    SUIT_HANDLE_INTENSIFY,
    SUIT_HANDLE_BANRELIC,
    SUIT_HANDLE_TRIGGERSKILL,
    SUIT_HANDLE_OPENSUIT,
    SUIT_HANDLE_CLOSESUIT,
    SUIT_HANDLE_ROLLTALENT,
    SUIT_HANDLE_REDUCESUITNUM,
    SUIT_HANDLE_SETTLEACCOUNTSSUIT,
    SUIT_HANDLE_TALENT2RELIC,
    SUIT_HANDLE_COINBANK,
    SUIT_HANDLE_NOCOSTREROLL,
    SUIT_HANDLE_SUITBACKRELIC,
    SUIT_HANDLE_EACHGETWHAT,
    SUIT_HANDLE_EACHREPLACE,
    SUIT_HANDLE_REFRESH_WEAPONGRADE]
BLANKRELIC = 5540
WAND_EQUIP = 0
WAND_UNEQUIP = 1
WAND_EQUIPCOMP = 2
WAND_UNEQUIPCOMP = 3
WAND_RECYCLE = 4
WANDCOMP_RECYCLE = 5
WAND_REMOVE = 6
WANDCOMP_REMOVE = 7
WANDPUT_INITIAL = 1
WANDPUT_SHOPBUY = 2
WANDCOMPPUT_INITIAL = 1
WANDCOMPPUT_SHOPBUY = 2
WANDTAG_PERFORM = 1
WANDTAG_WEAPON = 2
WANDTAG_FUNCTION = 3
WANDTAG_DAMAGE = 4
WANDTAG_GROWUP = 5
WANDTAG_OTHER = 6
WANDCOMP_RARITY_NORMAL = 1
WANDCOMP_RARITY_RARE = 2
WANDCOMP_RARITY_TALE = 3
WAND_CARDPACK = 0
WANDPUT_MAX_LAYER = 4
ABILITY_TYPE_NEGATIVE = 1
ABILITY_TYPE_POSITIVE = 2
ABILITY_TYPE_EXCLUSIVE = 3
ABILITY_QUALITY_NEGATIVE = 0
ABILITY_QUALITY_ONE = 1
ABILITY_QUALITY_TWO = 2
ABILITY_QUALITY_THREE = 3
ABILITY_QUALITY_FOUR = 4
FLOATING_ABILITY_QUALITY = [
    ABILITY_QUALITY_ONE,
    ABILITY_QUALITY_TWO,
    ABILITY_QUALITY_THREE,
    ABILITY_QUALITY_FOUR]
FIRE_RELIC = 5779
CORRISION_RELIC = 5780
THUNDER_RELIC = 5752
ALL_ELEMENT_SUIT = []
ALL_ELEMENT_RELIC = {
    THUNDER_RELIC: DAM_TYPE_THUNDER,
    CORRISION_RELIC: DAM_TYPE_CORRISION,
    FIRE_RELIC: DAM_TYPE_FIRE }
SUIT_ELEMENT = [
    DAM_TYPE_FIRE,
    DAM_TYPE_CORRISION,
    DAM_TYPE_THUNDER]
NORMALLOCK_RELICLABEL = 1
ILLUS_HIDESHOW_RELICLABEL = 2
CAN_REPICKUP = 3
CONSUMABLE = 4
BREED_RELIC_GROUP = 5
RECYCLE_DROP = 1
RECYCLE_UNDROP = 2
NORMAL_REDUCENUM_UI = 1
SUIT_REDUCENUM_UI = 2
JELLYFISH_SUMMON = 1
TENTACLE_SUMMON = 2
SUITEXPORT_PFSPECIALTAG = 1
THUMP_TYPE_NORMAL = 1
THUMP_TYPE_TRAP = 2
CEILINGLAMPSWITCH_ENABLE = 1
CEILINGLAMPSWITCH_DISABLE = 2
CEILINGLAMP_ENABLE = 3
CEILINGLAMP_DISABLE = 4
THUNDER_ENABLE = 1
THUNDER_CASTING = 2
THUNDER_CHARGE = 3
MONSTERAGENT_FLAG_NOCOMBAUSEPF = 1
DICE_SEASONCHALLENGE_UI = 1
BACKPACK_SEASONCHALLENGE_UI = 2
ADJUSTWEAPON_UI = 3
