# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_cscommondef/cs_itemdef.pyc
# RelativePath: clientlogic/cl_cscommondef/cs_itemdef.pyc
# Source Generated with Decompyle++
# File: cs_itemdef.pyc (Python 3.6)

ITEM_TYPE_NONE = 0
ITEM_SUBTYPE_OFFSET = 16
ITEM_MAIN_MASK = 0xFFFF0000
ITEM_CLASS_MASK = 0xFFFFFF00
ITEM_EXCE_MASK = 255
EQUIP_MASK_WEAPON = 65536
EQUIP_MASK_DEF = 131072
KEYITEM_MASK = 262144
SEASON_ITEM_MASK = 524288
MONSTER_GALLERY = 1048576
RAREITEM_MASK = 2097152
TRIGGER_MASK = 4194304
EQUIP_TYPE_MAINWEAPON = EQUIP_MASK_WEAPON | 4096
EQUIP_RIFLE = EQUIP_TYPE_MAINWEAPON | 1
EQUIP_SMG = EQUIP_TYPE_MAINWEAPON | 2
EQUIP_SHOTGUN = EQUIP_TYPE_MAINWEAPON | 3
EQUIP_HANDGUN = EQUIP_TYPE_MAINWEAPON | 4
EQUIP_SNIPER = EQUIP_TYPE_MAINWEAPON | 5
EQUIP_ROCKET_LAUNCHER = EQUIP_TYPE_MAINWEAPON | 6
EQUIP_LASER = EQUIP_TYPE_MAINWEAPON | 7
EQUIP_TYPE_CLOSEWEAPON = EQUIP_TYPE_MAINWEAPON | 8
EQUIP_TYPE_AMULET = EQUIP_TYPE_MAINWEAPON | 9
EQUIP_TYPE_FUNDAMENTALWEAPON = EQUIP_MASK_WEAPON | 32768
KEYITEM_CANNONBALL = KEYITEM_MASK | 1
KEYITEM_PARTYREWARD = KEYITEM_MASK | 2
WAND_MASK = SEASON_ITEM_MASK | 1
DICE_MASK = SEASON_ITEM_MASK | 2
MODULE_MASK = SEASON_ITEM_MASK | 3
CRYSTAL_MASK = SEASON_ITEM_MASK | 4
GEMITEM_MASK = SEASON_ITEM_MASK | 5
THIRDITEM_MASK = SEASON_ITEM_MASK | 6
QUALITY_TYPE_LOW = 1
QUALITY_TYPE_NORMAL = 2
QUALITY_TYPE_HIGH = 4
QUALITY_TYPE_CURSE = 8
ALL_QUALITY_DESORDER = (QUALITY_TYPE_HIGH, QUALITY_TYPE_NORMAL, QUALITY_TYPE_LOW, QUALITY_TYPE_CURSE)
QUALITY_FACTOR = {
    QUALITY_TYPE_CURSE: 120,
    QUALITY_TYPE_HIGH: 120,
    QUALITY_TYPE_NORMAL: 100,
    QUALITY_TYPE_LOW: 80 }
WEAPON_LIMIT = 0
INSCRIPTION_LIMIT = 1
MAIN_HOLD = 1
DEPUTY_HOLD = 2
ALL_HOLD = MAIN_HOLD | DEPUTY_HOLD
TRIGGER_AUTO = TRIGGER_MASK | 1
TRIGGER_SINGLE = TRIGGER_MASK | 2
TRIGGER_CONTINUE = TRIGGER_MASK | 3
TRIGGER_AUTO_CHARGE = TRIGGER_MASK | 4
TRIGGER_SINGLE_CHARGE = TRIGGER_MASK | 5
TRIGGER_DOWN_UP = TRIGGER_MASK | 6
TRIGGER_UP_FIRE = TRIGGER_MASK | 7
TRIGGER_FLYSWORD = TRIGGER_MASK | 8
TRIGGER_AUTOFIRE = TRIGGER_MASK | 9
TRIGGER_DOWN_SAVE = TRIGGER_MASK | 10
EMPTY_HAND_UNWIELDTIME = 10
BULLET_GRENADER = 4508
WEAPON_ACTION_UPGRADE = 1
WEAPON_ACTION_RECAST = 2
WEAPON_ACTION_UPGRADEINSCRIPTION = 3
WEAPON_ACTION_ENHANCE = 4
WEAPON_ACTION_INSC_ONE_NOR2RARE = 5
WEAPON_ACTION_INSC_ALL_NOR2RARE = 6
WEAPON_ACTION_INSC_ONE_NORRARE2EXCLU = 7
WEAPON_HOLD = 'Hold'
WEAPON_SNIPE = 'Snipe'
ITEM_GRADE_MIN = 0
ITEM_SOURCE_DEF = 0
ITEM_SOURCE_DROP = 1
ITEM_SOURCE_GOOD = 2
ITEM_SOURCE_CHOOSE = 3
ITEM_SOURCE_NPCREWARD = 4
ITEM_SOURCE_TALENT = 5
ITEM_SOURCE_SURVIVOR = 6
ITEM_BUFF_TYPE = 1
ITEM_DEBUFF_TYPE = 2
ITEM_ALL_TYPE = 3
ALL_BULLET = (4502, 4503, 4504)
ITEM_MODE_DRILLFOCUS = 1
SHOP_ITEM_CHANGE_REASON_NONE = 1
SHOP_ITEM_CHANGE_REASON_BENEDICTION = 2
