# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_cscommondef/cs_mgdef.pyc
# RelativePath: clientlogic/cl_cscommondef/cs_mgdef.pyc
# Source Generated with Decompyle++
# File: cs_mgdef.pyc (Python 3.6)

MG_SOURCE_KILLMONSTER = 1
MG_SOURCE_SMASHOBSTACLE = 2
MG_SOURCE_NPCREWARD = 3
MG_SOURCE_KILLSUMMON = 4
MG_SOURCE_KILLMONSTEREXT = 5
MG_SOURCE_RELIC = 6
MG_SOURCE_ELITEPHASEREWARD = 7
MG_SOURCE_PHASECHALLENGE = 8
MG_SOURCE_AIKILLBOSS = 9
MG_SOURCE_SEASONSUIT = 10
MG_SOURCE_SEASONMODULE = 11
MG_BULLET = 1
MG_CASH = 2
MG_EQUIP = 4
MG_RELIC = 5
MG_TRIGGER = 6
MG_KEY = 8
MG_TALENT = 9
MG_GOLDENCUP = 10
MG_GSCASH = 11
MG_KEYITEM = 12
MG_AUTOPERFORM = 13
MG_EXPERIENCE = 14
MG_RAREITEM = 15
MG_TASK = 16
MG_WAND = 17
MG_DICESELECT = 18
MG_DICE = 19
MG_DROP_HP = 401
