# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_cscommondef/cs_playmode.pyc
# RelativePath: clientlogic/cl_cscommondef/cs_playmode.pyc
# Source Generated with Decompyle++
# File: cs_playmode.pyc (Python 3.6)

from cllib.lib_only import RunMobileData
from cllib import lib_flag
MEMBER_TYPE_SQUAD = 1
MEMBER_TYPE_SOLO = 2
MEMBER_TYPE_DUO = 3
PLAY_TYPE_MULTI = 1
PLAY_TYPE_SINGLE = 2
ROUND_MAX = 3
CYCLE_MAX = 10
MOBILE_CYCLE_MAX = 9
DIFFICULTY_COMMON_ROUND = 1
DIFFICULTY_ADVANCE_CYCLE = 2
ROUND_NORMAL = 1
ROUND_ELITE = 2
ROUND_NIGHTMARE = 3
MAX_LAYER = 4
MODE_REIKICONNECT = 1001
MODE_SNOWMOUNTAINS = 1002
MODE_RIDINGALONE = 1003
MODE_MONSTERRELIC = 1004
MODE_WEAPONSTORE = 1005
MODE_TALENTFUSION = 1006
MODE_TASK = 1007
MODE_REAL_ENDLESS = 1008
MODETYPE_TO_ELEMENT = {
    MODE_REAL_ENDLESS: 'RealEndlessElement',
    MODE_TASK: 'TaskElement',
    MODE_TALENTFUSION: 'TalentFusionElement',
    MODE_WEAPONSTORE: 'WeaponStoreElement',
    MODE_MONSTERRELIC: 'MonsterRelicElement',
    MODE_RIDINGALONE: 'RidingAloneElement',
    MODE_SNOWMOUNTAINS: 'SnowMountainElement',
    MODE_REIKICONNECT: 'SuitElement' }
ALL_MODETYPE = [
    MODE_REIKICONNECT,
    MODE_SNOWMOUNTAINS,
    MODE_RIDINGALONE,
    MODE_MONSTERRELIC,
    MODE_WEAPONSTORE,
    MODE_TALENTFUSION,
    MODE_TASK,
    MODE_REAL_ENDLESS]
ENDLESS_BASE = 1
ENDLESS_TIME = 2
ENDLESS_REAL = 3
PLAYMODE_TEST = 1001
PLAYMODE_ROGUELIKE = 1002
PLAYMODE_ART_A1 = 1003
PLAYMODE_ART_B1 = 1004
PLAYMODE_ART_A2 = 1005
PLAYMODE_ART_B2 = 1006
PLAYMODE_LEVEL_TEST = 1007
PLAYMODE_ART_TEST = 1008
PLAYMODE_ART_DEMO = 1009
PLAYMODE_TEAM_BOSS = 1010
PLAYMODE_NEWBIE = 1011
PLAYMODE_ART_DEMO2 = 1012
PLAYMODE_DAYLY_TRIAL = 1013
PLAYMODE_NEWBIE2 = 1014
PLAYMODE_TEST_MOBILE = 1015
PLAYMODE_MOBILE_DEMO = 1016
PLAYMODE_SURVIVOR = 1017
PLAYMODE_NEWSURVIVOR = 1018
PLAYMODE_TO_NAME = {
    PLAYMODE_SURVIVOR: '幸存者模式',
    PLAYMODE_MOBILE_DEMO: '手游试玩',
    PLAYMODE_TEST_MOBILE: '手游测试',
    PLAYMODE_DAYLY_TRIAL: '每日试炼',
    PLAYMODE_NEWBIE: '新手引导',
    PLAYMODE_TEAM_BOSS: '组队BOSS',
    PLAYMODE_ART_DEMO2: '第二幕体验',
    PLAYMODE_ART_DEMO: '第一幕体验',
    PLAYMODE_ART_TEST: '美术测试',
    PLAYMODE_ROGUELIKE: '完整挑战',
    PLAYMODE_TEST: '测试战场' }
PLAYMODE_TO_WARNO = {
    PLAYMODE_NEWSURVIVOR: 3030,
    PLAYMODE_SURVIVOR: 3020,
    PLAYMODE_DAYLY_TRIAL: 3008,
    PLAYMODE_ART_DEMO2: 3007,
    PLAYMODE_ART_DEMO: 3005,
    PLAYMODE_NEWBIE: 3011,
    PLAYMODE_TEST: 3004,
    PLAYMODE_TEAM_BOSS: 3003,
    PLAYMODE_ART_TEST: 3002,
    PLAYMODE_ROGUELIKE: 3001 }
MOBILE_PLAYMODE_TO_WARNO = {
    PLAYMODE_NEWSURVIVOR: 3030,
    PLAYMODE_MOBILE_DEMO: 3010,
    PLAYMODE_TEST_MOBILE: 3012,
    PLAYMODE_DAYLY_TRIAL: 3009,
    PLAYMODE_ART_DEMO2: 3001,
    PLAYMODE_ART_DEMO: 3010,
    PLAYMODE_NEWBIE: 3011,
    PLAYMODE_TEST: 3004,
    PLAYMODE_TEAM_BOSS: 3003,
    PLAYMODE_ART_TEST: 3002,
    PLAYMODE_ROGUELIKE: 3007 }
WARNO_TO_PLAYMODE = {
    3001: PLAYMODE_ROGUELIKE,
    3002: PLAYMODE_ART_TEST,
    3003: PLAYMODE_TEAM_BOSS,
    3004: PLAYMODE_TEST,
    3005: PLAYMODE_ART_DEMO,
    3011: PLAYMODE_NEWBIE,
    3007: PLAYMODE_ART_DEMO2,
    3008: PLAYMODE_DAYLY_TRIAL,
    3020: PLAYMODE_SURVIVOR,
    3030: PLAYMODE_NEWSURVIVOR }
MOBILE_WARNO_TO_PLAYMODE = {
    3007: PLAYMODE_ROGUELIKE,
    3002: PLAYMODE_ART_TEST,
    3003: PLAYMODE_TEAM_BOSS,
    3004: PLAYMODE_TEST,
    3010: PLAYMODE_ART_DEMO,
    3011: PLAYMODE_NEWBIE,
    3001: PLAYMODE_ART_DEMO2,
    3009: PLAYMODE_DAYLY_TRIAL,
    3010: PLAYMODE_MOBILE_DEMO,
    3012: PLAYMODE_TEST_MOBILE,
    3030: PLAYMODE_NEWSURVIVOR }
PLAYMODE_IN_SERVER = {
    PLAYMODE_SURVIVOR: 1,
    PLAYMODE_ROGUELIKE: 1 }
MAX_ROUND = {
    PLAYMODE_NEWSURVIVOR: ROUND_MAX,
    PLAYMODE_MOBILE_DEMO: 1,
    PLAYMODE_TEST_MOBILE: ROUND_MAX,
    PLAYMODE_NEWBIE2: 1,
    PLAYMODE_DAYLY_TRIAL: 2,
    PLAYMODE_ART_DEMO2: 1,
    PLAYMODE_ART_DEMO: 1,
    PLAYMODE_NEWBIE: 1,
    PLAYMODE_TEST: 1,
    PLAYMODE_TEAM_BOSS: 1,
    PLAYMODE_ART_TEST: 1,
    PLAYMODE_ROGUELIKE: ROUND_MAX }
MAX_MEMBERNUM = {
    PLAYMODE_ROGUELIKE: 4 }
MAX_CYCLE = {
    1: 0,
    2: 0,
    3: CYCLE_MAX }
MOBILE_MAX_CYCLE = {
    1: 0,
    2: 0,
    3: MOBILE_CYCLE_MAX }

def GetWarNo(iPlayMode):
    if RunMobileData():
        if iPlayMode in MOBILE_PLAYMODE_TO_WARNO:
            return MOBILE_PLAYMODE_TO_WARNO[iPlayMode]
        return 0
    if iPlayMode in PLAYMODE_TO_WARNO:
        return PLAYMODE_TO_WARNO[iPlayMode]
    return 0


def GetPlayMode(iWarNo):
    if RunMobileData():
        if iWarNo in MOBILE_WARNO_TO_PLAYMODE:
            return MOBILE_WARNO_TO_PLAYMODE[iWarNo]
        return 0
    if iWarNo in WARNO_TO_PLAYMODE:
        return WARNO_TO_PLAYMODE[iWarNo]
    return 0


def GetMaxRound(iPlayMode):
    if iPlayMode in MAX_ROUND:
        return MAX_ROUND[iPlayMode]
    return 1


def GetMaxCycle(iRound):
    if RunMobileData():
        if iRound in MOBILE_MAX_CYCLE:
            return MOBILE_MAX_CYCLE[iRound]
        return 0
    if iRound in MAX_CYCLE:
        return MAX_CYCLE[iRound]
    return 0


def GetPlayModeName(iPlayMode):
    if iPlayMode in PLAYMODE_TO_NAME:
        return PLAYMODE_TO_NAME[iPlayMode]
    return ''


def GetAllModeType():
    return ALL_MODETYPE


def GetServerPlayMode():
    return PLAYMODE_IN_SERVER


def GetAllCanAddGsCashPlayMode():
    return {
        PLAYMODE_ROGUELIKE,
        PLAYMODE_DAYLY_TRIAL,
        PLAYMODE_TEST_MOBILE,
        PLAYMODE_SURVIVOR,
        PLAYMODE_NEWSURVIVOR}


def GetSeasonEffectivePlayMode():
    return (PLAYMODE_ROGUELIKE, PLAYMODE_DAYLY_TRIAL, PLAYMODE_SURVIVOR, PLAYMODE_NEWSURVIVOR)


def GetMaxMemberNum(iPlayMode):
    if iPlayMode in MAX_MEMBERNUM:
        return MAX_MEMBERNUM[iPlayMode]
    return 1

