# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_cscommondef/cs_virtualitem.pyc
# RelativePath: clientlogic/cl_cscommondef/cs_virtualitem.pyc
# Source Generated with Decompyle++
# File: cs_virtualitem.pyc (Python 3.6)


def GetItemShowName(iItemType, iSID, iAmount):
    import cl_item
    import cl_hero
    import cl_perform
    if iItemType == VIRTUAL_ITEM_CASH:
        return '金币×%d' % iAmount
    if iItemType == VIRTUAL_ITEM_EXP:
        return '经验×%d' % iAmount
    if iItemType == VIRTUAL_ITEM_ACTIVITYPOINT:
        return '活跃度×%d' % iAmount
    if iItemType == VIRTUAL_ITEM_RPLGOLD:
        return '钻石×%d' % iAmount
    if iSID:
        oItem = cl_item.GetTemp(iSID)
        if oItem:
            return oItem.m_Name
        if iItemType == REWARD_UNLOCK_HERO:
            oHero = cl_hero.GetHeroData(iSID)
            if oHero:
                return oHero.m_HeroName
        if iItemType == REWARD_UNLOCK_RELIC:
            oPerform = cl_perform.GetPerformModule(iSID)
            if oPerform:
                return oPerform.m_Name
    return '未知物品'

REWARD_TYPE_WEIGHT = 1
REWARD_TYPE_LIST = 2
REWARD_TYPE_DEFAULT = REWARD_TYPE_WEIGHT
VIRTUAL_ITEM_DROP = 1
VIRTUAL_ITEM_SHOPREFRESH = 2
VIRTUAL_ITEM_ATTR = 3
VIRTUAL_ITEM_EQUIP = 4
VIRTUAL_ITEM_RELIC = 5
VIRTUAL_ITEM_BULLET = 6
VIRTUAL_ITEM_AUTOPERFORM = 7
VIRTUAL_ITEM_KEY = 9
VIRTUAL_ITEM_PASSIVE = 10
VIRTUAL_ITEM_WARCASH = 11
VIRTUAL_UNLOCK_INITWEAPONDROP = 12
VIRTUAL_ITEM_TALENT = 13
VIRTUAL_ITEM_GOLDENCUP = 14
VIRTUAL_ITEM_EXTGSCASHDROP = 15
VIRTUAL_ITEM_HIDESHOPGOODS = 16
VIRTUAL_ITEM_WEAPONUPGRADE = 17
VIRTUAL_ITEM_EXCLUSINSCRIPTION = 18
VIRTUAL_ITEM_GEMINI = 19
VIRTUAL_ITEM_INSCRIPTIONPROP = 20
VIRTUAL_ITEM_KEYITEM = 21
VIRTUAL_ITEM_GSCASHRELIFE = 22
VIRTUAL_ITEM_RELIFETEAM = 23
VIRTUAL_ITEM_SHOPGOODSWEIGHT = 24
VIRTUAL_ITEM_TALENTWEIGHT = 25
VIRTUAL_ITEM_RAREITEM = 26
VIRTUAL_ITEM_MAGICPOWER = 27
VIRTUAL_ITEM_DEVICECOMP = 28
VIRTUAL_ITEM_PET = 29
VIRTUAL_ITEM_WANDCARDPACK = 30
VIRTUAL_ITEM_WAND = 32
VIRTUAL_ITEM_WANDCOMP = 33
VIRTUAL_ITEM_RANDOM = 34
VIRTUAL_ITEM_DICE = 35
VIRTUAL_ITEM_DICEPACKET = 36
VIRTUAL_ITEM_S7CRYSTAL = 37
VIRTUAL_ITEM_S7MODULE = 38
VIRTUAL_ITEM_S7CRYSTALPACKET = 39
VIRTUAL_ITEM_S8THIRDPERFORM = 40
VIRTUAL_ITEM_S8GEMITEM = 41
VIRTUAL_ITEM_SUBITEM = 97
VIRTUAL_ITEM_SUBTALENT = 98
VIRTUAL_ITEM_CASH = 100
VIRTUAL_ITEM_EXP = 101
VIRTUAL_ITEM_ACTIVITYPOINT = 103
VIRTUAL_ITEM_GARNISH = 104
VIRTUAL_ITEM_EQUIPSKIN = 105
VIRTUAL_ITEM_RPLGOLD = 106
REWARD_UNLOCK_WAEAPON = 109
REWARD_UNLOCK_RELIC = 110
REWARD_UNLOCK_HERO = 111
REWARD_TALENTUPGRADE = 112
REWARD_HEROUPGRADE = 113
REWARD_RESERVECASH = 114
WAR_UNLOCK_DAYTRIAL = 115
VIRTUAL_ITEM_CHEEK = 116
VIRTUAL_ITEM_AVATAR = 117
VIRTUAL_ITEM_EMOTION = 118
WAR_UNLOCK_SURVIVOR = 119
REWARD_UNLOCK_MODULE = 120
WAR_UNLOCK_NEWSURVIVOR = 121
REWARD_UNLOCK_WEAPONSKIN = 122
REWARD_UNLOCK_STANDBYACTION = 123
WAR_UNLOCK_PETCONFUNC = 124
WAR_UNLOCK_SEASONSUITTEMP = 125
WAR_UNLOCK_CUSTOMSEASONSUITTEMP = 126
WAR_UNLOCK_SEASONSUITCARDPACK = 127
WAR_UNLOCK_SEASONWANDCARRY = 128
WAR_UNLOCK_WANDPUT = 129
WAR_UNLOCK_SHOPWANDCOMPPUT = 130
WAR_SET_SHOPWANDCOMPEXCLUDEPUT = 131
WAR_UNLOCK_SEASONWANDABILITY = 132
WAR_UNLOCK_DICEPUT = 133
WAR_UNLOCK_DICEPRESETTEMP = 134
WAR_UNLOCK_S7MODULE = 135
WAR_UNLOCK_S7CRYSTAL = 136
