# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_engobjconf.pyc
# RelativePath: clientlogic/cl_engobjconf.pyc
# Source Generated with Decompyle++
# File: cl_engobjconf.pyc (Python 3.6)

from cl_commondefines import NWARRIOR_NPC_RAREGOLDENCUP, WARRIOR_NORPART, WARRIOR_ELIPART, WARRIOR_SCENEQUERY_ENTITYEFFECT, PAMOD_TYPE_QUERRY, WARRIOR_HERO, PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, NAV_TYPE_FLY, NAV_TYPE_NULL, WARRIOR_BOSSDM, WARRIOR_BOSSCANNON, WARRIOR_MONSTER, NWARRIOR_NPC_CAR, NWARRIOR_NPC, NAV_TYPE_OBSTACLE, PAMOD_TYPE_DYNA, PAMOD_TYPE_NULL, NWARRIOR_NPC_TRANSFER, NWARRIOR_NPC_GOLDENCUP, NWARRIOR_NPC_LIMITGOLDENCUP, NWARRIOR_NPC_EXCHANGEGOLDENCUP, NWARRIOR_DROP, WARRIOR_INCUBATOR, WARRIOR_PERFORM, WARRIOR_ENTITYEFFECT, WARRIOR_PHYSXENTITYEFFECT, WARRIOR_MOVEEFFECT, WARRIOR_OBSTACLE, WARRIOR_PROTEGE_NORMAL, WARRIOR_AIRWALL_PHY, WARRIOR_OBSTACLE_BROKENPILLAR, WARRIOR_OBSTACLE_LVTRIDESTORY, WARRIOR_OBSTACLE_TRIDESTROY, WARRIOR_OBSTACLE_VICCTRL, WARRIOR_OBSTACLE_NORMAL, WARRIOR_OBSTACLE_BUNKER, WARRIOR_TRAP_SMASH, WARRIOR_TRAP_UPSTONE, WARRIOR_BUILD_TRAP, WARRIOR_STONEPILLAR, WARRIOR_TRAP_ROTATEPILLAR, WARRIOR_NOPHYSMOVEEFFECT, WARRIOR_NODURABILITY, WARRIOR_NORFLY, WARRIOR_PERFORM_BUILD, WARRIOR_LUOHOU_PILLAR, WARRIOR_SERVANT, WARRIOR_TRAP_FAKERPLANK, PAMOD_TYPE_TRDYNA, NWARRIOR_NPC_PHASEGOLDENCUP, NWARRIOR_NPC_PHASESHOP, NWARRIOR_NPC_PHASESMITH, WARRIOR_DEVICE_BARRIER, WARRIOR_SUMMON_STELE, WARRIOR_DEVICE_TURRET, WARRIOR_INKWALL, WARRIOR_SUMMON_BARRIER, WARRIOR_PET, WARRIOR_PET_MINI, WARRIOR_PET_HEROSIDE, WARRIOR_PET_MINICLONE, WARRIOR_MONSTERBUILD, WARRIOR_MONSTERHINDER, WARRIOR_MONSTENOPHYRHINDER, WARRIOR_SUMMON_SEED, WARRIOR_TRAP_THUNDERBUCKET, WARRIOR_MOVEBUILD
from cl_pxlayer import PXLAYER_TRIGGERDYNA, PXLAYER_ENTITYEFFECT_NOSTATIC, PXLAYER_AIRWALL, PXLAYER_BOX, PXLAYER_DOOR, PXLAYER_RBULLET, PXLAYER_ENTITYEFFECT, PXLAYER_TRANSPARENT, PXLAYER_NULL, PXLAYER_NPC, PXLAYER_MONSTER, PXLAYER_PLAYER, PXLAYER_SERVANT, PXLAYER_BARRIER, PXLAYER_DEVICE_TURRET, PXLAYER_INKWALL, PXLAYER_ENEMY_BUILD, PXMASK_TRANSPARENT
g_EngObjConf = {
    WARRIOR_SUMMON_SEED: (PAMOD_TYPE_DYNA, NAV_TYPE_NULL, PXLAYER_TRANSPARENT),
    WARRIOR_SUMMON_BARRIER: (PAMOD_TYPE_DYNA, NAV_TYPE_NULL, PXLAYER_BARRIER),
    WARRIOR_DEVICE_BARRIER: (PAMOD_TYPE_TRDYNA, NAV_TYPE_NULL, PXLAYER_BARRIER),
    WARRIOR_DEVICE_TURRET: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_DEVICE_TURRET),
    WARRIOR_MOVEBUILD: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_ENEMY_BUILD),
    WARRIOR_MONSTENOPHYRHINDER: (PAMOD_TYPE_NULL, NAV_TYPE_OBSTACLE, PXLAYER_ENEMY_BUILD),
    WARRIOR_MONSTERHINDER: (PAMOD_TYPE_TRDYNA, NAV_TYPE_NULL, PXLAYER_TRIGGERDYNA),
    WARRIOR_TRAP_THUNDERBUCKET: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_TRAP_FAKERPLANK: (PAMOD_TYPE_TRDYNA, NAV_TYPE_NULL, PXLAYER_TRIGGERDYNA),
    WARRIOR_TRAP_ROTATEPILLAR: (PAMOD_TYPE_DYNA, NAV_TYPE_NULL, PXLAYER_DOOR),
    WARRIOR_TRAP_SMASH: (PAMOD_TYPE_DYNA, NAV_TYPE_NULL, PXLAYER_BOX),
    WARRIOR_TRAP_UPSTONE: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_DOOR),
    WARRIOR_BUILD_TRAP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    WARRIOR_MONSTERBUILD: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_ENEMY_BUILD),
    WARRIOR_SUMMON_STELE: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_ENEMY_BUILD),
    WARRIOR_LUOHOU_PILLAR: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_PERFORM_BUILD: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_STONEPILLAR: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_PROTEGE_NORMAL: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_PLAYER),
    WARRIOR_AIRWALL_PHY: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_AIRWALL),
    WARRIOR_OBSTACLE_BROKENPILLAR: (PAMOD_TYPE_NULL, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_OBSTACLE_LVTRIDESTORY: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_DOOR),
    WARRIOR_OBSTACLE_TRIDESTROY: (PAMOD_TYPE_DYNA, NAV_TYPE_NULL, PXLAYER_DOOR),
    WARRIOR_OBSTACLE_VICCTRL: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_OBSTACLE_BUNKER: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_DOOR),
    WARRIOR_OBSTACLE_NORMAL: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_BOX),
    WARRIOR_OBSTACLE: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_DOOR),
    WARRIOR_NOPHYSMOVEEFFECT: (PAMOD_TYPE_NULL, NAV_TYPE_CROWDAGENT, PXLAYER_RBULLET),
    WARRIOR_SCENEQUERY_ENTITYEFFECT: (PAMOD_TYPE_QUERRY, NAV_TYPE_NULL, PXLAYER_ENTITYEFFECT_NOSTATIC),
    WARRIOR_PHYSXENTITYEFFECT: (PAMOD_TYPE_DYNA, NAV_TYPE_NULL, PXLAYER_ENTITYEFFECT),
    WARRIOR_MOVEEFFECT: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_RBULLET),
    WARRIOR_INCUBATOR: (PAMOD_TYPE_DYNA, NAV_TYPE_CROWDAGENT, PXLAYER_TRANSPARENT),
    WARRIOR_INKWALL: (PAMOD_TYPE_TRDYNA, NAV_TYPE_NULL, PXLAYER_INKWALL),
    WARRIOR_ENTITYEFFECT: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_ENTITYEFFECT),
    WARRIOR_PERFORM: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_TRANSPARENT),
    NWARRIOR_DROP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_EXCHANGEGOLDENCUP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_PHASEGOLDENCUP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_PHASESMITH: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_PHASESHOP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_RAREGOLDENCUP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_LIMITGOLDENCUP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_GOLDENCUP: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    NWARRIOR_NPC_TRANSFER: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NPC),
    NWARRIOR_NPC_CAR: (PAMOD_TYPE_DYNA, NAV_TYPE_CROWDAGENT, PXLAYER_NPC),
    NWARRIOR_NPC: (PAMOD_TYPE_DYNA, NAV_TYPE_OBSTACLE, PXLAYER_NPC),
    WARRIOR_NORFLY: (PAMOD_TYPE_CTRL, NAV_TYPE_FLY, PXLAYER_MONSTER),
    WARRIOR_NODURABILITY: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_MONSTER),
    WARRIOR_ELIPART: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    WARRIOR_NORPART: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    WARRIOR_BOSSCANNON: (PAMOD_TYPE_CTRL, NAV_TYPE_NULL, PXLAYER_MONSTER),
    WARRIOR_BOSSDM: (PAMOD_TYPE_CTRL, NAV_TYPE_NULL, PXLAYER_MONSTER),
    WARRIOR_MONSTER: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_MONSTER),
    WARRIOR_PET_HEROSIDE: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_SERVANT),
    WARRIOR_PET_MINI: (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL),
    WARRIOR_PET_MINICLONE: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_SERVANT),
    WARRIOR_PET: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_SERVANT),
    WARRIOR_SERVANT: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_SERVANT),
    WARRIOR_HERO: (PAMOD_TYPE_CTRL, NAV_TYPE_CROWDAGENT, PXLAYER_PLAYER) }

def GetEngineObjConf(iFightType):
    if iFightType in g_EngObjConf:
        return g_EngObjConf[iFightType]
    if iFightType & WARRIOR_HERO:
        return g_EngObjConf[WARRIOR_HERO]
    if iFightType & WARRIOR_MONSTER:
        return g_EngObjConf[WARRIOR_MONSTER]
    if iFightType & WARRIOR_OBSTACLE == WARRIOR_OBSTACLE:
        return g_EngObjConf[WARRIOR_OBSTACLE]
    if iFightType & WARRIOR_BUILD_TRAP == WARRIOR_BUILD_TRAP:
        return g_EngObjConf[WARRIOR_BUILD_TRAP]
    if iFightType & NWARRIOR_NPC:
        return g_EngObjConf[NWARRIOR_NPC]
    if iFightType & NWARRIOR_DROP:
        return g_EngObjConf[NWARRIOR_DROP]
    if iFightType & WARRIOR_SERVANT:
        return g_EngObjConf[WARRIOR_SERVANT]
    return (PAMOD_TYPE_NULL, NAV_TYPE_NULL, PXLAYER_NULL)

