# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_forbid.pyc
# RelativePath: clientlogic/cl_forbid.pyc
# Source Generated with Decompyle++
# File: cl_forbid.pyc (Python 3.6)

from cl_commondefines import FORBID_ATTACK, FORBID_AUTO_ATTACK, FORBID_AUTO_FILLBULLET, FORBID_BREAKSHIELDRECOVER, FORBID_DASH, FORBID_DEVICE_ACTIVE, FORBID_DEVICE_OPEN, FORBID_DROPWEAPON, FORBID_FILLBULLET, FORBID_FOCUS, FORBID_JUMP, FORBID_MINOR, FORBID_MONSTERPF, FORBID_MOVE, FORBID_OPACTION, FORBID_OPENPACKAGEPANEL, FORBID_OPENSNIPE, FORBID_OPSKILL, FORBID_PUSHED, FORBID_RECYCLE, FORBID_ROTATE, FORBID_SERVANT_SWITCH, FORBID_SHIELDCURE, FORBID_SHIELDRECOVER, FORBID_SWITCHOVER_DEVICE, FORBID_SWITCHWEAPON, FORBID_SWITCHWEAPONATTPF, FORBID_THROW, FORBID_UNIONPF, FORBID_USECAREERPF, FORBID_USEDRUG, FORBID_WEAPONATIVE
g_Rule2Forbid = {
    1002: { },
    1003: {
        FORBID_MINOR: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1004: {
        FORBID_OPSKILL: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1 },
    1005: {
        FORBID_MINOR: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1006: { },
    1007: {
        FORBID_DASH: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_PUSHED: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1008: {
        FORBID_MOVE: 1 },
    1009: {
        FORBID_USEDRUG: 1 },
    1010: {
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1011: { },
    1012: {
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1014: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1015: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1016: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1017: {
        FORBID_JUMP: 1,
        FORBID_MOVE: 1 },
    1018: {
        FORBID_DASH: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_PUSHED: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1019: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_SWITCHWEAPON: 1 },
    1020: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1021: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1023: {
        FORBID_JUMP: 1 },
    1025: {
        FORBID_MINOR: 1,
        FORBID_JUMP: 1,
        FORBID_MOVE: 1 },
    1027: {
        FORBID_USECAREERPF: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_USEDRUG: 1,
        FORBID_ATTACK: 1 },
    1028: {
        FORBID_ATTACK: 1 },
    1029: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1030: {
        FORBID_ROTATE: 1,
        FORBID_PUSHED: 1,
        FORBID_JUMP: 1 },
    1031: {
        FORBID_MINOR: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1 },
    1032: { },
    1033: {
        FORBID_SHIELDRECOVER: 1 },
    1034: { },
    1035: {
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1036: {
        FORBID_USECAREERPF: 1,
        FORBID_JUMP: 1,
        FORBID_MOVE: 1 },
    1037: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_ROTATE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1038: {
        FORBID_MONSTERPF: 1,
        FORBID_JUMP: 1,
        FORBID_MOVE: 1,
        FORBID_ATTACK: 1 },
    1039: {
        FORBID_MONSTERPF: 1,
        FORBID_ATTACK: 1 },
    1040: {
        FORBID_ROTATE: 1,
        FORBID_PUSHED: 1,
        FORBID_JUMP: 1 },
    1041: {
        FORBID_BREAKSHIELDRECOVER: 1 },
    1042: {
        FORBID_ROTATE: 1 },
    1043: {
        FORBID_MONSTERPF: 1,
        FORBID_ATTACK: 1 },
    1044: {
        FORBID_USEDRUG: 1 },
    1045: {
        FORBID_MINOR: 1,
        FORBID_ATTACK: 1 },
    1046: {
        FORBID_SHIELDCURE: 1,
        FORBID_SHIELDRECOVER: 1 },
    1047: {
        FORBID_JUMP: 1,
        FORBID_MOVE: 1 },
    1048: {
        FORBID_MINOR: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1049: {
        FORBID_JUMP: 1,
        FORBID_ATTACK: 1 },
    1050: {
        FORBID_JUMP: 1,
        FORBID_MOVE: 1,
        FORBID_ATTACK: 1 },
    1051: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_UNIONPF: 1,
        FORBID_SWITCHWEAPONATTPF: 1,
        FORBID_MINOR: 1,
        FORBID_SHIELDRECOVER: 1,
        FORBID_PUSHED: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1052: {
        FORBID_UNIONPF: 1,
        FORBID_USECAREERPF: 1,
        FORBID_MOVE: 1 },
    1053: {
        FORBID_MOVE: 1 },
    1054: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_UNIONPF: 1,
        FORBID_SWITCHWEAPONATTPF: 1,
        FORBID_MINOR: 1,
        FORBID_SHIELDRECOVER: 1,
        FORBID_PUSHED: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1055: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1056: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1057: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1058: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1059: {
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1 },
    1060: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_RECYCLE: 1,
        FORBID_DROPWEAPON: 1,
        FORBID_OPENPACKAGEPANEL: 1,
        FORBID_MINOR: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_SWITCHWEAPON: 1 },
    1061: {
        FORBID_USECAREERPF: 1 },
    1062: {
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1063: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1064: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_DROPWEAPON: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1065: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_DROPWEAPON: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1066: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_ATTACK: 1 },
    1067: {
        FORBID_PUSHED: 1,
        FORBID_JUMP: 1,
        FORBID_MOVE: 1 },
    1068: {
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1069: {
        FORBID_MINOR: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1070: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_FOCUS: 1,
        FORBID_SWITCHWEAPONATTPF: 1,
        FORBID_MINOR: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1071: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_FOCUS: 1,
        FORBID_MINOR: 1,
        FORBID_USECAREERPF: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1072: {
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1073: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1074: {
        FORBID_PUSHED: 1,
        FORBID_OPENSNIPE: 1 },
    1075: {
        FORBID_ATTACK: 1 },
    1076: {
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_ATTACK: 1 },
    1077: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_PUSHED: 1,
        FORBID_SWITCHWEAPON: 1 },
    1078: {
        FORBID_PUSHED: 1 },
    1079: {
        FORBID_MINOR: 1 },
    1080: {
        FORBID_ATTACK: 1 },
    1081: {
        FORBID_ATTACK: 1 },
    1082: {
        FORBID_OPSKILL: 1 },
    1083: {
        FORBID_SERVANT_SWITCH: 1,
        FORBID_USECAREERPF: 1 },
    1084: {
        FORBID_USECAREERPF: 1 },
    1085: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_SERVANT_SWITCH: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1086: {
        FORBID_ATTACK: 1 },
    1087: {
        FORBID_MONSTERPF: 1,
        FORBID_ROTATE: 1,
        FORBID_SHIELDRECOVER: 1,
        FORBID_PUSHED: 1,
        FORBID_JUMP: 1,
        FORBID_MOVE: 1,
        FORBID_ATTACK: 1 },
    1088: {
        FORBID_AUTO_FILLBULLET: 1 },
    1089: {
        FORBID_AUTO_FILLBULLET: 1,
        FORBID_FOCUS: 1,
        FORBID_DROPWEAPON: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1090: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_SWITCHWEAPON: 1 },
    1091: {
        FORBID_DEVICE_OPEN: 1,
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1092: {
        FORBID_DEVICE_OPEN: 1,
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1093: {
        FORBID_DEVICE_OPEN: 1,
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1094: {
        FORBID_MINOR: 1 },
    1095: {
        FORBID_ATTACK: 1 },
    1096: {
        FORBID_OPENSNIPE: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1097: {
        FORBID_FILLBULLET: 1 },
    1098: {
        FORBID_USECAREERPF: 1,
        FORBID_JUMP: 1 },
    1099: {
        FORBID_MINOR: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_ATTACK: 1 },
    1100: {
        FORBID_AUTO_ATTACK: 1,
        FORBID_OPSKILL: 1,
        FORBID_FOCUS: 1,
        FORBID_MINOR: 1,
        FORBID_PUSHED: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_ATTACK: 1 },
    1101: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_DROPWEAPON: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_ATTACK: 1 },
    1102: {
        FORBID_MOVE: 1 },
    1103: {
        FORBID_OPACTION: 1,
        FORBID_DASH: 1,
        FORBID_RECYCLE: 1,
        FORBID_DROPWEAPON: 1,
        FORBID_MINOR: 1,
        FORBID_SHIELDRECOVER: 1,
        FORBID_PUSHED: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_USEDRUG: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1104: {
        FORBID_MOVE: 1 },
    1105: {
        FORBID_UNIONPF: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_JUMP: 1,
        FORBID_OPENSNIPE: 1 },
    1106: {
        FORBID_USECAREERPF: 1,
        FORBID_JUMP: 1,
        FORBID_ATTACK: 1 },
    1107: {
        FORBID_UNIONPF: 1 },
    1108: {
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_MOVE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1109: {
        FORBID_USECAREERPF: 1,
        FORBID_JUMP: 1 },
    1110: {
        FORBID_PUSHED: 1 },
    1111: {
        FORBID_PUSHED: 1 },
    1112: {
        FORBID_DEVICE_ACTIVE: 1,
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_OPSKILL: 1,
        FORBID_MINOR: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1113: {
        FORBID_SWITCHOVER_DEVICE: 1,
        FORBID_WEAPONATIVE: 1,
        FORBID_ATTACK: 1 },
    1114: {
        FORBID_THROW: 1 },
    1115: {
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 },
    1116: {
        FORBID_WEAPONATIVE: 1,
        FORBID_USECAREERPF: 1,
        FORBID_THROW: 1,
        FORBID_OPENSNIPE: 1,
        FORBID_SWITCHWEAPON: 1,
        FORBID_FILLBULLET: 1,
        FORBID_ATTACK: 1 } }
SNIPE_RULE = 1006
DIE_RULE = 1007
JUMP_RULE = 1009
DARTLE_RULE = 1011
ENTERBUILD_RULE = 1013
DYING_RULE = 1018
PUSHED_RULE = 1030
DASH_RULE = 1034
FALL_RULE = 1023
PUSHCTRL_RULE = 1036
MONSJUMP_RULE = 1039
IMMOBILIZE_RULE = 1040
DASHCTRL_RULE = 1044
SHIELDLOCK_RULE = 1046
SIGHTFORBID_RULE = 1060
NAVSEEK_RULE = 1067
AIRLINE_RULE = 1078
HATCH_RULE = 1087
AUTO_FILLBULLET_RULE = 1088
TEAMAI_GM_RULE = 1102

def GetRule2Forbid(iRule):
    return g_Rule2Forbid[iRule]

if 'g_ForbidVersion' not in globals():
    g_ForbidVersion = 1
    g_ForbidVersionInfo = { }
else:
    g_ForbidVersion += 1
g_ForbidVersionInfo[g_ForbidVersion] = g_Rule2Forbid

def GetRule2ForbidVersion(iVer, iRule):
    return g_ForbidVersionInfo[iVer][iRule]

