# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_pxlayer.pyc
# RelativePath: clientlogic/cl_pxlayer.pyc
# Source Generated with Decompyle++
# File: cl_pxlayer.pyc (Python 3.6)

import C_frgame
PXLAYER_NULL = 0
PXLAYER_STATIC = 1
PXLAYER_SEVENT = 2
PXLAYER_AIRWALL = 3
PXLAYER_IMPENETRABLE = 4
PXLAYER_PLAYER = 5
PXLAYER_MONSTER = 6
PXLAYER_NPC = 7
PXLAYER_DOOR = 8
PXLAYER_BOX = 9
PXLAYER_BUCKET = 10
PXLAYER_EBULLET = 11
PXLAYER_RBULLET = 12
PXLAYER_TRANSPARENT = 13
PXLAYER_DEVENT = 14
PXLAYER_RBULLET_OUTER = 15
PXLAYER_RBULLET_INNER = 16
PXLAYER_ENTITYEFFECT = 17
PXLAYER_TRIDSTEVENT = 18
PXLAYER_RBULLET_NOMONS = 19
PXLAYER_RBULLET_OUTER_NOMONS = 20
PXLATER_PETROCHEMICAL_OUTER = 21
PXLAYER_BARRIER = 22
PXLAYER_ENTITYEFFECT_NOSTATIC = 23
PXLAYER_EBULLET_STATIC = 24
PXLAYER_PLAYER_DYING = 25
PXLAYER_SERVANT = 26
PXLAYER_TRIGGERDYNA = 27
PXLAYER_DEVICE_TURRET = 28
PXLAYER_INKWALL = 29
PXLAYER_ENEMY_BUILD = 30
PXGROUP_NULL = 0
PXGROUP_STATIC = 1
PXGROUP_SEVENT = 2
PXGROUP_AIRWALL = 3
PXGROUP_IMPENETRABLE = 4
PXGROUP_PLAYER = 5
PXGROUP_MONSTER = 6
PXGROUP_NPC = 7
PXGROUP_DOOR = 8
PXGROUP_BOX = 9
PXGROUP_BUCKET = 10
PXGROUP_EBULLET = 11
PXGROUP_RBULLET = 12
PXGROUP_TRANSPARENT = 13
PXGROUP_DEVENT = 14
PXGROUP_RBULLET_OUTER = 15
PXGROUP_RBULLET_INNER = 16
PXGROUP_ENTITYEFFECT = 17
PXGROUP_TRIDSTEVENT = 18
PXGROUP_RBULLET_NOMONS = 19
PXGROUP_RBULLET_OUTER_NOMONS = 20
PXGROUP_PETROCHEMICAL_OUTER = 21
PXGROUP_BARRIER = 22
PXGROUP_ENTITYEFFECT_NOSTATIC = 23
PXGROUP_EBULLET_STATIC = 24
PXGROUP_PLAYER_DYING = 25
PXGROUP_SERVANT = 26
PXGROUP_TRIGGERDYNA = 27
PXGROUP_DEVICE_TURRET = 28
PXGROUP_INKWALL = 29
PXGROUP_ENEMY_BUILD = 30
PXMASK_NULL = 1
PXMASK_STATIC = 2
PXMASK_SEVENT = 4
PXMASK_AIRWALL = 8
PXMASK_IMPENETRABLE = 16
PXMASK_PLAYER = 32
PXMASK_MONSTER = 64
PXMASK_NPC = 128
PXMASK_DOOR = 256
PXMASK_BOX = 512
PXMASK_BUCKET = 1024
PXMASK_EBULLET = 2048
PXMASK_RBULLET = 4096
PXMASK_TRANSPARENT = 8192
PXMASK_DEVENT = 16384
PXMASK_RBULLET_OUTER = 32768
PXMASK_RBULLET_INNER = 65536
PXMASK_ENTITYEFFECT = 131072
PXMASK_TRIDSTEVENT = 262144
PXMASK_RBULLET_NOMONS = 524288
PXMASK_RBULLET_OUTER_NOMONS = 1048576
PXMASK_PETROCHEMICAL_OUTER = 2097152
PXMASK_BARRIER = 4194304
PXMASK_ENTITYEFFECT_NOSTATIC = 8388608
PXMASK_EBULLET_STATIC = 16777216
PXMASK_PLAYER_DYING = 33554432
PXMASK_SERVANT = 67108864
PXMASK_TRIGGERDYNA = 134217728
PXMASK_DEVICE_TURRET = 268435456
PXMASK_INKWALL = 536870912
PXMASK_ENEMY_BUILD = 1073741824
PXMASK_BLOCK = PXMASK_STATIC | PXMASK_NPC | PXMASK_DOOR | PXMASK_PETROCHEMICAL_OUTER
PXMASK_SKILLBLK = PXMASK_BLOCK | PXMASK_IMPENETRABLE
PXMASK_SIGHTBLK = PXMASK_SKILLBLK | PXMASK_BOX | PXMASK_BUCKET
PXMASK_SIDEBLK = PXMASK_SKILLBLK | PXMASK_BARRIER | PXMASK_INKWALL
PXMASK_GROUNDBLK = PXMASK_BLOCK | PXMASK_AIRWALL | PXMASK_BOX | PXMASK_BUCKET | PXMASK_ENEMY_BUILD | PXMASK_IMPENETRABLE
PXMASK_MOVEBLK = PXMASK_BLOCK | PXMASK_AIRWALL | PXMASK_BOX | PXMASK_BUCKET | PXMASK_MONSTER | PXMASK_ENEMY_BUILD
PXMASK_OBJECT = PXMASK_PLAYER | PXMASK_MONSTER | PXMASK_NPC | PXMASK_DOOR | PXMASK_BOX | PXMASK_BUCKET | PXMASK_ENTITYEFFECT | PXMASK_ENEMY_BUILD
PXMASK_LIVEOBJ = PXMASK_PLAYER | PXMASK_MONSTER | PXMASK_BOX | PXMASK_BUCKET | PXMASK_ENTITYEFFECT | PXMASK_ENTITYEFFECT_NOSTATIC | PXMASK_BARRIER | PXMASK_INKWALL | PXMASK_SERVANT | PXMASK_DEVICE_TURRET | PXMASK_ENEMY_BUILD
PXMASK_ENEMYBLK = PXMASK_BLOCK | PXMASK_BOX | PXMASK_BUCKET | PXMASK_MONSTER | PXMASK_ENEMY_BUILD
g_PxGroupMap = {
    PXGROUP_ENEMY_BUILD: (PXGROUP_RBULLET,),
    PXGROUP_INKWALL: (),
    PXGROUP_DEVICE_TURRET: (PXGROUP_EBULLET, PXGROUP_RBULLET, PXGROUP_DEVENT, PXGROUP_EBULLET_STATIC, PXGROUP_RBULLET_OUTER, PXGROUP_RBULLET_OUTER_NOMONS, PXLAYER_RBULLET_NOMONS),
    PXGROUP_TRIGGERDYNA: (),
    PXGROUP_PLAYER_DYING: (PXGROUP_DEVENT,),
    PXGROUP_EBULLET_STATIC: (PXGROUP_PLAYER, PXGROUP_MONSTER, PXGROUP_SERVANT, PXGROUP_STATIC),
    PXGROUP_ENTITYEFFECT_NOSTATIC: (PXGROUP_PLAYER, PXGROUP_MONSTER, PXGROUP_SERVANT, PXGROUP_NPC, PXGROUP_DOOR, PXGROUP_BOX, PXGROUP_ENEMY_BUILD, PXGROUP_BUCKET, PXGROUP_IMPENETRABLE),
    PXGROUP_BARRIER: (),
    PXGROUP_PETROCHEMICAL_OUTER: (PXGROUP_RBULLET, PXGROUP_RBULLET_NOMONS, PXGROUP_RBULLET_OUTER_NOMONS, PXGROUP_RBULLET_OUTER, PXGROUP_RBULLET_INNER),
    PXGROUP_RBULLET_OUTER_NOMONS: (PXGROUP_PLAYER, PXGROUP_SERVANT, PXGROUP_NPC, PXGROUP_DOOR, PXGROUP_BOX, PXGROUP_ENEMY_BUILD, PXGROUP_BUCKET),
    PXGROUP_RBULLET_NOMONS: (PXGROUP_STATIC, PXGROUP_IMPENETRABLE, PXGROUP_PLAYER, PXGROUP_SERVANT, PXGROUP_NPC, PXGROUP_DOOR, PXGROUP_BOX, PXGROUP_ENEMY_BUILD, PXGROUP_BUCKET, PXGROUP_BARRIER, PXGROUP_INKWALL),
    PXGROUP_TRIDSTEVENT: (PXGROUP_MONSTER,),
    PXGROUP_ENTITYEFFECT: (PXGROUP_PLAYER, PXGROUP_MONSTER, PXGROUP_SERVANT, PXGROUP_NPC, PXGROUP_DOOR, PXGROUP_BOX, PXGROUP_ENEMY_BUILD, PXGROUP_BUCKET, PXGROUP_STATIC, PXGROUP_IMPENETRABLE),
    PXGROUP_RBULLET_INNER: (PXGROUP_STATIC, PXGROUP_IMPENETRABLE, PXGROUP_BARRIER, PXGROUP_INKWALL),
    PXGROUP_RBULLET_OUTER: (PXGROUP_PLAYER, PXGROUP_MONSTER, PXGROUP_SERVANT, PXGROUP_NPC, PXGROUP_DOOR, PXGROUP_BOX, PXGROUP_ENEMY_BUILD, PXGROUP_BUCKET),
    PXGROUP_DEVENT: (),
    PXGROUP_TRANSPARENT: (),
    PXGROUP_RBULLET: (PXGROUP_STATIC, PXGROUP_IMPENETRABLE, PXGROUP_PLAYER, PXGROUP_MONSTER, PXGROUP_SERVANT, PXGROUP_NPC, PXGROUP_DOOR, PXGROUP_BOX, PXGROUP_ENEMY_BUILD, PXGROUP_BUCKET, PXGROUP_DEVENT, PXGROUP_BARRIER, PXGROUP_INKWALL),
    PXGROUP_EBULLET: (PXGROUP_PLAYER, PXGROUP_MONSTER, PXGROUP_SERVANT),
    PXGROUP_BUCKET: (PXGROUP_RBULLET,),
    PXGROUP_BOX: (PXGROUP_RBULLET,),
    PXGROUP_DOOR: (PXGROUP_RBULLET,),
    PXGROUP_NPC: (PXGROUP_SEVENT, PXGROUP_RBULLET),
    PXGROUP_MONSTER: (PXGROUP_DEVENT, PXGROUP_EBULLET, PXGROUP_RBULLET),
    PXGROUP_SERVANT: (PXGROUP_DEVENT, PXGROUP_EBULLET, PXGROUP_RBULLET),
    PXGROUP_PLAYER: (PXGROUP_SEVENT, PXGROUP_DEVENT, PXGROUP_EBULLET, PXGROUP_RBULLET, PXGROUP_TRIGGERDYNA),
    PXGROUP_IMPENETRABLE: (),
    PXGROUP_AIRWALL: (),
    PXGROUP_SEVENT: (),
    PXGROUP_STATIC: () }
g_PxLayerMap = {
    PXLAYER_ENEMY_BUILD: (PXGROUP_ENEMY_BUILD, g_PxGroupMap[PXGROUP_ENEMY_BUILD], PXMASK_ENEMY_BUILD),
    PXLAYER_INKWALL: (PXGROUP_INKWALL, g_PxGroupMap[PXGROUP_INKWALL], PXMASK_INKWALL),
    PXLAYER_DEVICE_TURRET: (PXGROUP_DEVICE_TURRET, g_PxGroupMap[PXGROUP_DEVICE_TURRET], PXMASK_DEVICE_TURRET),
    PXLAYER_TRIGGERDYNA: (PXGROUP_TRIGGERDYNA, g_PxGroupMap[PXGROUP_TRIGGERDYNA], PXMASK_TRIGGERDYNA),
    PXLAYER_SERVANT: (PXGROUP_SERVANT, g_PxGroupMap[PXGROUP_SERVANT], PXMASK_SERVANT),
    PXLAYER_PLAYER_DYING: (PXGROUP_PLAYER_DYING, g_PxGroupMap[PXGROUP_PLAYER_DYING], PXMASK_PLAYER_DYING),
    PXLAYER_EBULLET_STATIC: (PXGROUP_EBULLET_STATIC, g_PxGroupMap[PXGROUP_EBULLET_STATIC], PXMASK_EBULLET_STATIC),
    PXLAYER_ENTITYEFFECT_NOSTATIC: (PXGROUP_ENTITYEFFECT_NOSTATIC, g_PxGroupMap[PXGROUP_ENTITYEFFECT_NOSTATIC], PXMASK_ENTITYEFFECT_NOSTATIC),
    PXLAYER_BARRIER: (PXGROUP_BARRIER, g_PxGroupMap[PXGROUP_BARRIER], PXMASK_BARRIER),
    PXLATER_PETROCHEMICAL_OUTER: (PXGROUP_PETROCHEMICAL_OUTER, g_PxGroupMap[PXGROUP_PETROCHEMICAL_OUTER], PXMASK_PETROCHEMICAL_OUTER),
    PXLAYER_RBULLET_OUTER_NOMONS: (PXGROUP_RBULLET_OUTER_NOMONS, g_PxGroupMap[PXGROUP_RBULLET_OUTER_NOMONS], PXMASK_RBULLET_OUTER_NOMONS),
    PXLAYER_RBULLET_NOMONS: (PXGROUP_RBULLET_NOMONS, g_PxGroupMap[PXGROUP_RBULLET_NOMONS], PXMASK_RBULLET_NOMONS),
    PXLAYER_TRIDSTEVENT: (PXGROUP_TRIDSTEVENT, g_PxGroupMap[PXGROUP_TRIDSTEVENT], PXMASK_TRIDSTEVENT),
    PXLAYER_ENTITYEFFECT: (PXGROUP_ENTITYEFFECT, g_PxGroupMap[PXGROUP_ENTITYEFFECT], PXMASK_ENTITYEFFECT),
    PXLAYER_RBULLET_INNER: (PXGROUP_RBULLET_INNER, g_PxGroupMap[PXGROUP_RBULLET_INNER], PXMASK_RBULLET_INNER),
    PXLAYER_RBULLET_OUTER: (PXGROUP_RBULLET_OUTER, g_PxGroupMap[PXGROUP_RBULLET_OUTER], PXMASK_RBULLET_OUTER),
    PXLAYER_DEVENT: (PXGROUP_DEVENT, g_PxGroupMap[PXGROUP_DEVENT], PXMASK_DEVENT),
    PXLAYER_TRANSPARENT: (PXGROUP_TRANSPARENT, g_PxGroupMap[PXGROUP_TRANSPARENT], PXMASK_TRANSPARENT),
    PXLAYER_RBULLET: (PXGROUP_RBULLET, g_PxGroupMap[PXGROUP_RBULLET], PXMASK_RBULLET),
    PXLAYER_EBULLET: (PXGROUP_EBULLET, g_PxGroupMap[PXGROUP_EBULLET], PXMASK_EBULLET),
    PXLAYER_BUCKET: (PXGROUP_BUCKET, g_PxGroupMap[PXGROUP_BUCKET], PXMASK_BUCKET),
    PXLAYER_BOX: (PXGROUP_BOX, g_PxGroupMap[PXGROUP_BOX], PXMASK_BOX),
    PXLAYER_DOOR: (PXGROUP_DOOR, g_PxGroupMap[PXGROUP_DOOR], PXMASK_DOOR),
    PXLAYER_NPC: (PXGROUP_NPC, g_PxGroupMap[PXGROUP_NPC], PXMASK_NPC),
    PXLAYER_MONSTER: (PXGROUP_MONSTER, g_PxGroupMap[PXGROUP_MONSTER], PXMASK_MONSTER),
    PXLAYER_PLAYER: (PXGROUP_PLAYER, g_PxGroupMap[PXGROUP_PLAYER], PXMASK_PLAYER),
    PXLAYER_IMPENETRABLE: (PXGROUP_IMPENETRABLE, g_PxGroupMap[PXGROUP_IMPENETRABLE], PXMASK_IMPENETRABLE),
    PXLAYER_AIRWALL: (PXGROUP_AIRWALL, g_PxGroupMap[PXGROUP_AIRWALL], PXMASK_AIRWALL),
    PXLAYER_SEVENT: (PXGROUP_SEVENT, g_PxGroupMap[PXGROUP_SEVENT], PXMASK_SEVENT),
    PXLAYER_STATIC: (PXGROUP_STATIC, g_PxGroupMap[PXGROUP_STATIC], PXMASK_STATIC) }
if 'g_Init' not in globals():
    g_Init = False

def InitPxLayer():
    global g_Init
    if g_Init:
        return None
    g_Init = C_frgame.InitPxLayer(g_PxLayerMap)
    if g_Init:
        print('pxlayer initialized')

