# Path: /Users//个人空间/04 Gunfire/converted/converted_data1/clientlogic/cl_duonet/duonetdata.pyc
# RelativePath: clientlogic/cl_duonet/duonetdata.pyc
# Source Generated with Decompyle++
# File: duonetdata.pyc (Python 3.6)

g_C2FS = {
    (86,): ('dn_cl_notify', False, {
        1: 'DN_C2GSChat',
        2: 'DN_C2GSWarAnswerConfirm' }),
    (74,): ('dn_cl_cnetwar', True, {
        **'DN_C2GSWarNewPing' }),
    (70,): ('dn_cl_cnetwar', True, {
        **'DN_C2GSEarphone' }),
    (71,): ('dn_cl_cnetwar', True, {
        **'DN_C2GSWarPing' }),
    (69,): ('dn_cl_cnetwar', True, {
        **'DN_C2GSFace' }),
    (68,): ('dn_cl_cnetwar', False, {
        1: 'DN_C2GSPickUp',
        2: 'DN_C2GSResetSpoolup',
        3: 'DN_C2GSSnipe',
        4: 'DN_C2GSHaltAction',
        5: 'DN_C2GSRelifeAnswer',
        7: 'DN_C2GSEnterWatch',
        8: 'DN_C2GSSwitchWeaponAttPF',
        9: 'DN_C2GSRemoveBeaconSummon',
        10: 'DN_C2GSTriggerBehavior',
        11: 'DN_C2GSTriggerCartoonList',
        12: 'DN_C2GSReplaceWeapon',
        13: 'DN_C2GSSwitchWatch',
        14: 'DN_C2GSNowInfo',
        15: 'DN_C2GSWeaponLockTarget',
        16: 'DN_C2GSTeamDamage',
        17: 'DN_C2GSStartRescue',
        18: 'DN_C2GSBreakRescue',
        19: 'DN_C2GSSaveInfo',
        20: 'DN_C2GSRelifeSetPhase',
        21: 'DN_C2GSChooseOption',
        22: 'DN_C2GSCallForHelp',
        23: 'DN_C2GSReportFPS',
        24: 'DN_C2GSRecycleDrop',
        25: 'DN_C2GSCheckImmortal',
        26: 'DN_C2GSClientEvent',
        27: 'DN_C2GSSkipCG',
        28: 'DN_C2GSSetTeamPF',
        29: 'DN_C2GSRefreshItemChecked',
        30: 'DN_C2GSCGState',
        31: 'DN_C2GSUpdateSealedInscription',
        32: 'DN_C2GSChooseReward',
        33: 'DN_C2GSPreviewUpgradeWeapon',
        34: 'DN_C2GSUpdateChooseRewardStatus',
        35: 'DN_C2GSUpdateVoteStatus',
        36: 'DN_C2GSChangeHeroName',
        37: 'DN_C2GSSetPrioritySuit',
        38: 'DN_C2GSRollRelic',
        39: 'DN_C2GSSetRelicUpgradeType',
        40: 'DN_C2GSViewSeasonTask',
        41: 'DN_C2GSRecycleGoldenCup',
        42: 'DN_C2GSRecycleUnDrop',
        43: 'DN_C2GSTalentLevelUp',
        44: 'DN_C2GSStartConquer',
        45: 'DN_C2GSHaltConquer',
        46: 'DN_C2GSModeAnswer',
        47: 'DN_C2GSHaltRepeatShoot',
        96: 'DN_C2GSUpdateDeviceCompLevel',
        97: 'DN_C2GSUpdateDeviceCompPos',
        98: 'DN_C2GSIceMoveDistance',
        99: 'DN_C2GSSeasonSuitOption',
        100: 'DN_C2GSSignRelic',
        101: 'DN_C2GSMarkSeasonSuit',
        102: 'DN_C2GSSetSuitTemp',
        103: 'DN_C2GSSwitchWeaponCliMode',
        104: 'DN_C2GSRealDiedRelife',
        105: 'DN_C2GSUpdateSkillCounter',
        106: 'DN_C2GSPickSeed' }),
    (109,): ('dn_cl_wand_net', False, {
        1: 'DN_C2GSWandOption',
        2: 'DN_C2GSWandCompOption',
        3: 'DN_C2GSBagCompOption',
        4: 'DN_C2GSClearWandRedDot',
        5: 'DN_C2GSClearCompRedDot',
        6: 'DN_C2GSBatchRecycleBagComp',
        7: 'DN_C2GSAddS5Sign',
        8: 'DN_C2GSDelS5Sign',
        9: 'DN_C2GSQuickAddComp',
        10: 'DN_C2GSLockWandAbility' }),
    (106,): ('dn_cl_container_talentcon', False, {
        1: 'DN_C2GSDisableTalent' }),
    (102,): ('dn_cl_perform_net', False, {
        1: 'DN_C2GSBulletRuleEnable',
        3: 'DN_C2GSBulletRuleDisable' }),
    (101,): ('dn_cl_signal_net', False, {
        1: 'DN_C2GSAddSceneSignal',
        2: 'DN_C2GSAddObjSignal',
        3: 'DN_C2GSAddNotifySignal',
        4: 'DN_C2GSDelSignal',
        5: 'DN_C2GSTeamInfoSignal',
        6: 'DN_C2GSAddPhotoSignal' }),
    (103,): ('dn_cl_seasonplay_net', False, {
        1: 'DN_C2GSRemoveS7Item',
        2: 'DN_C2GSEquipS7Item',
        3: 'DN_C2GSUnEquipS7Item',
        4: 'DN_C2GSRotateCrystal',
        5: 'DN_C2GSEnableModule',
        6: 'DN_C2GSAutoEquip',
        7: 'DN_C2GSAutoUnEquip',
        8: 'DN_C2GSLockCrystal',
        9: 'DN_C2GSS7ItemOperation',
        10: 'DN_C2GSSetS7ModuleSign',
        11: 'DN_C2GSRemoveS8Item',
        12: 'DN_C2GSEquipS8GemItem',
        13: 'DN_C2GSUnEquipS8GemItem' }),
    (64,): ('dn_cl_scene', False, {
        1: 'DN_C2GSLoadMapOK' }),
    (107,): ('dn_cl_container_reliccon', False, {
        1: 'DN_C2GSRemoveRelic',
        2: 'DN_C2GSRefreshRelic',
        3: 'DN_C2GSExchangeExtendRelic',
        4: 'DN_C2GSHandleTempRemoveRelic' }),
    (108,): ('dn_cl_container_petcon', False, {
        1: 'DN_C2GSSetCurPet',
        2: 'DN_C2GSSetHatchEggType',
        3: 'DN_C2GSUnsetNewPet',
        4: 'DN_C2GSOpenPetBag',
        5: 'DN_C2GSPetBagOption',
        6: 'DN_C2GSMarkPetAbility',
        7: 'DN_C2GSHatchEggNum',
        8: 'DN_C2GSChangePetLock' }),
    (80,): ('dn_cl_npc_net', False, {
        1: 'DN_C2GSNPCInteract',
        2: 'DN_C2GSAnswerList',
        3: 'DN_C2GSNpcRefresh',
        4: 'DN_C2GSAnswerValue',
        5: 'DN_C2GSNpcItemInteract',
        6: 'DN_C2GSNPCClientStopInteract',
        7: 'DN_C2GSAnswerDict',
        8: 'DN_C2GSAnswerValueList',
        9: 'DN_C2GSRandomRewardpf',
        10: 'DN_C2GSFarTransferLevel',
        11: 'DN_C2GSNPCItemConInteract',
        12: 'DN_C2GSChooseAll',
        13: 'DN_C2GSNpcLockGoods',
        14: 'DN_C2GSNPCInjectAnimaOperation',
        15: 'DN_C2GSNpcChooseRelicByFuse',
        16: 'DN_C2GSXiaoJiuModifyAnswerValue' }),
    (73,): ('dn_cl_movectrl_net', True, {
        **'DN_C2GSMoveBack' }),
    (72,): ('dn_cl_movectrl_net', False, {
        1: 'DN_C2GSMove',
        2: 'DN_C2GSDashExtInfo',
        3: 'DN_C2GSEscape' }),
    (83,): ('dn_cl_minigame_cnet', False, {
        1: 'DN_C2GSMiniGameOP' }),
    (104,): ('dn_cl_dice_net', False, {
        1: 'DN_C2GSRollDice',
        2: 'DN_C2GSAssembleDice',
        3: 'DN_C2GSDropDice',
        4: 'DN_C2GSClearDiceRedDot',
        5: 'DN_C2GSRecycleBagDice',
        6: 'DN_C2GSChooseDiceResult',
        7: 'DN_C2GSUseDiceSpecialItem',
        9: 'DN_C2GSAddS6Sign',
        10: 'DN_C2GSDelS6Sign',
        11: 'DN_C2GSUpdateUnLockAbilityDesc' }),
    (89,): ('dn_cl_gamedebug', False, {
        1: 'DN_C2GSFlowDebug',
        2: 'DN_C2GSSkillDebugStart',
        3: 'DN_C2GSSkillDebug',
        4: 'DN_C2GSReceiveSeed' }),
    (105,): ('dn_cl_item_cnet', False, {
        1: 'DN_C2GSItemContainerOp',
        2: 'DN_C2GSUseRareItem',
        3: 'DN_C2GSChangeItemMode' }),
    (84,): ('dn_cl_build_net', False, {
        1: 'DN_C2GSBuildInteract',
        2: 'DN_C2GSBuildStopInteract' }) }
g_ProcessedProtoSetC2FS = frozenset({
    64,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    80,
    83,
    84,
    86,
    89,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109})
g_MultiSubC2FS = {
    64: None,
    68: None,
    69: None,
    70: None,
    71: None,
    72: None,
    73: None,
    74: None,
    80: None,
    83: None,
    84: None,
    86: None,
    89: None,
    101: None,
    102: None,
    103: None,
    104: None,
    105: None,
    106: None,
    107: None,
    108: None,
    109: None }
